// CLR does not provie us open mixin types yet. All DeclaringType members thus must be in the same package. 
// How to overcome this?
// C# has extensionmethods for that.

[Constructor()]
/*async*/ interface GIFEncoder
{
	void setRepeat(long p);
	void setDelay(long p);

	void setSize(long x, long y);

	void start();
	void addFrame(any canvas2d);
	void setTransparent(any color);

	/*
	RewriteToAssembly error: System.NotSupportedException: Uint8ClampedArray
	at jsc.meta.Commands.Reference.ReferenceUltraSource.Plugins.IDLCompiler.<>c__DisplayClass53.<Define>b__2c(IDLTypeReference SourceType)
	*/
	/*async*/ void addFrame(Uint8ClampedArray canvas2d, boolean is_imageData);

	void finish();

	// async void finish(Action<string> yield) { yield(stream()); }

	// can we define some code here inline?
	// do we need roslyn to help us out?
	// would this define an extension from IDL?

	GIFEncoder.ByteArray stream();
};


interface GIFEncoder.ByteArray
{
	string getData();
};