using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using java.applet;
using ScriptCoreLib;
using ScriptCoreLib.ActionScript;
using ScriptCoreLib.ActionScript.flash.display;
using ScriptCoreLib.JavaScript.DOM.HTML;

namespace Ultra1
{
	[ScriptApplicationEntryPoint]
	public class UltraApplication
	{
		[SWF]
		public class MySprite : Sprite
		{
			public MySprite()
			{
				// creating the flash object 
				// + stratus
				// + alchemy

			}
		}

		public class MyApplet : Applet
		{

			public override void init()
			{
				// creating the java applet

			}
		}

		// possible names:
		// 1. application
		// 2. document
		// 3. element
		// 4. control

		public UltraApplication(IHTMLElement e)
		{
			// we are attaching to the DOM now after onload event
			// bootstrap code was generated by jsc.meta and is using ScriptCoreLib
		}
	}
}
