using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using java.applet;
using ScriptCoreLib;
using ScriptCoreLib.ActionScript;
using ScriptCoreLib.ActionScript.flash.display;
using ScriptCoreLib.JavaScript.DOM.HTML;
using ScriptCoreLib.JavaScript.Extensions;
using ScriptCoreLib.JavaScript;
using ScriptCoreLib.ActionScript.Extensions;
using java.awt;

namespace Ultra1
{
	[ScriptApplicationEntryPoint(Width = DefaultWidth, Height = DefaultHeight)]
	[SWF(width = DefaultWidth, height = DefaultHeight)]
	public class UltraSprite : Sprite
	{
		public const int DefaultWidth = 500;
		public const int DefaultHeight = 400;

		public UltraSprite()
		{
			// creating the flash object 
			// + stratus
			// + alchemy

			// funny :) i have forgotten how to write anything
			// on flash API ... too much WPF API?
			var r = new Sprite();

			r.graphics.beginFill(0x7070);
			r.graphics.drawRect(8, 8, 64, 64);

			
			r.AttachTo(this);
		}
	}

	[ScriptApplicationEntryPoint(Width = DefaultWidth, Height = DefaultHeight)]
	public class UltraApplet : Applet
	{
		public const int DefaultWidth = 500;
		public const int DefaultHeight = 400;


		public override void init()
		{
			base.resize(DefaultWidth, DefaultHeight);
			// creating the java applet

		}

		static Color GetBlue(double b)
		{
			int u = (int)(0xff * b);

			return new Color(u);
		}

		public override void paint(global::java.awt.Graphics g)
		{
			// old school gradient :)

			var h = this.getHeight();
			var w = this.getWidth();

			for (int i = 0; i < h; i++)
			{

				g.setColor(GetBlue(1 - (double)i / (double)h));
				g.drawLine(0, i, w, i);
			}
		}
	}

	[ScriptApplicationEntryPoint]
	public class UltraApplication
	{
		

		// possible names:
		// 1. application
		// 2. document
		// 3. element
		// 4. control

		public UltraApplication(IHTMLElement e)
		{
			// we are attaching to the DOM now after onload event
			// bootstrap code was generated by jsc.meta and is using ScriptCoreLib

			{
				var x = new IHTMLButton("create UltraSprite");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{
						#region new UltraSprite().AttachToDocument()
						var o = new IHTMLEmbed();

						//o.src = @"..\..\Ultra1.UltraSprite\web\UltraSprite.swf";
						// jsc.meta has embedded the objects for us...
						o.src = @"assets/Ultra1.UltraApplication/UltraSprite.swf";
						o.style.SetSize(UltraSprite.DefaultWidth, UltraSprite.DefaultHeight);
						o.AttachToDocument();
						#endregion

					};
			}

			{
				var x = new IHTMLButton("create UltraApplet");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{
						#region new UltraApplet().AttachToDocument()
						var o = new IHTMLApplet();

						// see: http://java.sun.com/j2se/1.4.2/docs/guide/plugin/developer_guide/java_js.html
						//o.archive = @"..\..\Ultra1.UltraApplet\web\bin\Ultra1.UltraApplet.jar";
						// jsc.meta has embedded the objects for us...
						o.archive = @"assets/Ultra1.UltraApplication/UltraApplet.jar";
						o.mayscript = true;
						o.code = "Ultra1.UltraApplet";
						o.width = UltraApplet.DefaultWidth;
						o.height = UltraApplet.DefaultHeight;

						//o.style.SetSize(UltraSprite.DefaultWidth, UltraSprite.DefaultHeight);
						o.AttachToDocument();
						#endregion

					};
			}
		}


	}
}
