using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using java.applet;
using ScriptCoreLib;
using ScriptCoreLib.ActionScript;
using ScriptCoreLib.ActionScript.flash.display;
using ScriptCoreLib.JavaScript.DOM.HTML;
using ScriptCoreLib.JavaScript.Extensions;
using ScriptCoreLib.JavaScript;

namespace Ultra1
{
	[ScriptApplicationEntryPoint]
	[SWF]
	public class UltraSprite : Sprite
	{
		public UltraSprite()
		{
			// creating the flash object 
			// + stratus
			// + alchemy

		}
	}

	[ScriptApplicationEntryPoint]
	public class UltraApplet : Applet
	{

		public override void init()
		{
			// creating the java applet

		}
	}

	[ScriptApplicationEntryPoint]
	public class UltraApplication
	{
		

		// possible names:
		// 1. application
		// 2. document
		// 3. element
		// 4. control

		public UltraApplication(IHTMLElement e)
		{
			// we are attaching to the DOM now after onload event
			// bootstrap code was generated by jsc.meta and is using ScriptCoreLib

			var x = new IHTMLButton("Ultra!");

			x.AttachToDocument();

			x.onclick +=
				delegate
				{
					Native.Window.alert("hello by "  + x.innerText);
				};
		}


	}
}
