using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoGeneratedReferences.Components
{
	static class ExtensibleAlphaExtensions
	{
		public static ExtensibleAlpha ToExtensibleAlpha(this string e)
		{
			return new ExtensibleAlpha { More = e };
		}
	}
}
