using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using java.applet;
using java.awt;
using ScriptCoreLib;
using ScriptCoreLib.ActionScript;
using ScriptCoreLib.ActionScript.Extensions;
using ScriptCoreLib.ActionScript.flash.display;
using ScriptCoreLib.JavaScript;
using ScriptCoreLib.JavaScript.DOM;
using ScriptCoreLib.JavaScript.DOM.HTML;
using ScriptCoreLib.JavaScript.Extensions;
using AvalonExampleGallery.Shared;
using System.Windows.Controls;

namespace Ultra5
{

	//[Description("OrcasClientScriptApplication. Write javascript, flash and java applets within a C# project.")]

	public sealed class UltraApplication
	{
		public sealed class UltraApplet : Applet
		{
			public const int DefaultWidth = 500;
			public const int DefaultHeight = 400;


			public override void init()
			{
				base.resize(DefaultWidth, DefaultHeight);
				// creating the java applet

			}

			static Color GetBlue(double b)
			{
				int u = (int)(0xff * b);

				return new Color(u);
			}

			public override void paint(global::java.awt.Graphics g)
			{
				// old school gradient :)

				var h = this.getHeight();
				var w = this.getWidth();

				for (int i = 0; i < h; i++)
				{

					g.setColor(GetBlue(1 - (double)i / (double)h));
					g.drawLine(0, i, w, i);
				}
			}
		}



		public sealed class UltraSprite : Sprite
		{
			public const int DefaultWidth = AvalonExampleGalleryCanvas.DefaultWidth;
			public const int DefaultHeight = AvalonExampleGalleryCanvas.DefaultHeight;

			readonly AvalonExampleGalleryCanvas Content = new AvalonExampleGalleryCanvas();

			public UltraSprite()
			{
				Content.AttachToContainer<Canvas>(this);


			}

			public event AvalonExampleGalleryCanvas.ViewSelected AtViewSelected
			{
				add
				{
					Content.AtViewSelected += value;
				}
				remove
				{
					Content.AtViewSelected -= value;
				}
			}
		}

		public UltraApplication(IHTMLElement e)
		{
			// we are attaching to the DOM now after onload event
			// bootstrap code was generated by jsc.meta and is using ScriptCoreLib

			var status = new IHTMLDiv { innerText = "Select a view in WPF!" }.AttachToDocument();
			
			var ee = new IHTMLDiv();
			ee.style.position = IStyle.PositionEnum.relative;
			ee.style.SetSize(UltraSprite.DefaultWidth, UltraSprite.DefaultHeight);
			ee.style.overflow = IStyle.OverflowEnum.auto;

			Native.Document.body.style.overflow = IStyle.OverflowEnum.auto;

			{
				var x = new IHTMLButton("WPF in flash!");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{

						var o = new UltraSprite();

						var x1 = new IHTMLButton("attach events!");

						x1.AttachToDocument();

						x1.onclick +=
							delegate
							{
								o.AtViewSelected +=
									t =>
									{
										status.innerText = "WPF selects " + t;
									};
							};

						o.AttachSpriteTo(ee);


					};
			}

		

			{
				var x = new IHTMLButton("WPF in javascript!");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{
					

						var o = new AvalonExampleGalleryCanvas();

						o.AtViewSelected +=
							t =>
							{
								status.innerText = "WPF selects " + t;
							};

						var eee = new IHTMLDiv();
						eee.style.position = IStyle.PositionEnum.relative;
						eee.AttachTo(ee);

						o.AttachToContainer(eee);
					};
			}


			{
				var x = new IHTMLButton("create UltraApplet proxied");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{

						var o = new UltraApplet();

						o.AttachAppletTo(ee);
					};
			}

			ee.AttachToDocument();

		}


	}
}
