// http://www.w3.org/TR/XMLHttpRequest2/

[Constructor,
 Constructor(html::HTMLFormElement form)]
interface FormData {
  void append(DOMString name, Blob value, optional DOMString filename);
  void append(DOMString name, DOMString value);
};