// http://www.w3.org/TR/XMLHttpRequest2/
// http://www.w3.org/TR/XMLHttpRequest/
// http://src.chromium.org/viewvc/blink/trunk/Source/core/html/FormData.idl

[Constructor,
 Constructor(html::HTMLFormElement form)]
interface FormData {
  void append(DOMString name, Blob value, optional DOMString filename);
  void append(DOMString name, DOMString value);
};