using java.applet;
using java.awt.@event;
using System;

namespace jDOSBoxAppletWithWarcraft
{
    public sealed class ApplicationApplet : jdos.gui.MainApplet
    {
        public const int DefaultWidth = 800;
        public const int DefaultHeight = 600;


        int x;
        int y;


        public void __MainApplet_mousePressed()
        {
            //Console.WriteLine("__MainApplet_mousemove " + new { x, y });

            var e = new MouseEvent(
                this,
                MouseEvent.MOUSE_PRESSED,
                0,
                0,
                x,
                y,
                0,
                false
            );

            mousePressed(e);
        }
   
        public void __MainApplet_mouseReleased()
        {
            //Console.WriteLine("__MainApplet_mousemove " + new { x, y });

            var e = new MouseEvent(
                this,
                MouseEvent.MOUSE_RELEASED,
                0,
                0,
                x,
                y,
                0,
                false
            );

            mouseReleased(e);
        }

        public void __MainApplet_mousemove(string dx, string dy)
        {
            x += int.Parse(dx);
            y += int.Parse(dy);

            x = x.Min(640).Max(0);
            y = y.Min(480).Max(0);

            //Console.WriteLine("__MainApplet_mousemove " + new { x, y });

            var e = new MouseEvent(
                this,
                MouseEvent.MOUSE_MOVED,
                0,
                0,
                x,
                y,
                0,
                false
            );

            mouseMoved(e);
        }

        public void __MainApplet_keyPressed(string _key, string _char, Action<string> yield)
        {
            //            KeyEvent(Component source, int id, long when, int modifiers, int keyCode, char keyChar) 
            //source - the Component that originated the event
            //id - an integer identifying the type of event
            //when - a long integer that specifies the time the event occurred
            //modifiers - the modifier keys down during event (shift, ctrl, alt, meta) Either extended _DOWN_MASK or old _MASK modifiers should be used, but both models should not be mixed in one event. Use of the extended modifiers is preferred.
            //keyCode - the integer code for an actual key, or VK_UNDEFINED (for a key-typed event)
            //keyChar - the Unicode character generated by this event, or CHAR_UNDEFINED (for key-pressed and key-released events which do not map to a valid Unicode character)
            try
            {
                var __keyCode = int.Parse(_key);
                var __keyChar = int.Parse(_char);

                //if (__keyChar == 0)
                //    __keyChar = KeyEvent.CHAR_UNDEFINED;


                //Console.WriteLine("__MainApplet_keyPressed " + new { __keyCode, __keyChar });

                base.keyPressed(
                    new java.awt.@event.KeyEvent(
                        this,
                        KeyEvent.KEY_PRESSED,
                        0,
                        __keyCode,
                        __keyChar
                    )
                );
            }
            catch (Exception ex)
            {
                yield(new { ex.Message }.ToString());
            }
        }

        public void __MainApplet_keyReleased(string _key, string _char, Action<string> yield)
        {
            try
            {
                var __keyCode = int.Parse(_key);
                var __keyChar = int.Parse(_char);

                //if (__keyChar == 0)
                //    __keyChar = KeyEvent.CHAR_UNDEFINED;


                //Console.WriteLine("__MainApplet_keyReleased " + new { __keyCode, __keyChar });

                base.keyReleased(
                    new java.awt.@event.KeyEvent(
                        this,
                        KeyEvent.KEY_RELEASED,
                        0,
                       __keyCode,
                       __keyChar
                    )
                );
            }
            catch (Exception ex)
            {
                yield(new { ex.Message }.ToString());
            }

        }
    }
}
