/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.jtb.modelview;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f040005;
        public static final int blue=0x7f040006;
        public static final int darkgray=0x7f040007;
        public static final int darkslategray=0x7f040008;
        public static final int model_border=0x7f040002;
        public static final int model_header=0x7f040003;
        public static final int row_alt=0x7f040000;
        public static final int row_main=0x7f040001;
        public static final int white=0x7f040004;
    }
    public static final class drawable {
        public static final int file=0x7f020000;
        public static final int folder=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int obj=0x7f020003;
        public static final int off=0x7f020004;
        public static final int unknown=0x7f020005;
    }
    public static final class id {
        public static final int about_item=0x7f07000d;
        public static final int bottomLeftText=0x7f070003;
        public static final int bottomRightText=0x7f070006;
        public static final int help_item=0x7f07000b;
        public static final int home_item=0x7f07000a;
        public static final int icon=0x7f070001;
        public static final int llright=0x7f070004;
        public static final int modelInfoDate=0x7f070008;
        public static final int modelInfoPath=0x7f070007;
        public static final int modelSurfaceView=0x7f070009;
        public static final int preferences_item=0x7f07000e;
        public static final int report_item=0x7f07000c;
        public static final int row=0x7f070000;
        public static final int topLeftText=0x7f070002;
        public static final int topRightText=0x7f070005;
    }
    public static final class layout {
        public static final int browse_activity=0x7f030000;
        public static final int list_row=0x7f030001;
        public static final int model_activity=0x7f030002;
        public static final int prefs=0x7f030003;
    }
    public static final class menu {
        public static final int modelview_menu=0x7f060000;
    }
    public static final class string {
        public static final int acknowlegements=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int change_log=0x7f050002;
        public static final int url_help=0x7f050003;
        public static final int url_home=0x7f050004;
        public static final int url_report=0x7f050005;
    }
}
