/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.elasticdroid;

public final class R {
    public static final class array {
        public static final int monitorinstanceview_duration_array=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int ami=0x7f020000;
        public static final int droid_guy=0x7f020001;
        public static final int green_light=0x7f020002;
        public static final int ic_dialog_time=0x7f020003;
        public static final int ic_lock_lock=0x7f020004;
        public static final int ic_menu_chart=0x7f020005;
        public static final int ic_menu_elasticdroid=0x7f020006;
        public static final int ic_menu_invite=0x7f020007;
        public static final int ic_menu_login=0x7f020008;
        public static final int ic_menu_manage=0x7f020009;
        public static final int ic_menu_mapmode=0x7f02000a;
        public static final int ic_menu_mylocation=0x7f02000b;
        public static final int ic_menu_play_clip=0x7f02000c;
        public static final int ic_menu_refresh=0x7f02000d;
        public static final int ic_menu_stop=0x7f02000e;
        public static final int ic_menu_view=0x7f02000f;
        public static final int icon=0x7f020010;
        public static final int instance=0x7f020011;
        public static final int keypair=0x7f020012;
        public static final int linux_penguin=0x7f020013;
        public static final int red_light=0x7f020014;
        public static final int ssh=0x7f020015;
        public static final int tag=0x7f020016;
        public static final int widget_bg=0x7f020017;
        public static final int yellow_light=0x7f020018;
    }
    public static final class id {
        public static final int CheckedTextView01=0x7f070027;
        public static final int RelativeScrollView=0x7f070014;
        public static final int about_content=0x7f070000;
        public static final int akEntry=0x7f070018;
        public static final int akTextView=0x7f070017;
        public static final int changeButton=0x7f070023;
        public static final int chart=0x7f07001d;
        public static final int dashboard_menuitem_about=0x7f070037;
        public static final int dashboard_menuitem_another_user=0x7f070036;
        public static final int dashboard_menuitem_default_region=0x7f070035;
        public static final int dashboard_menuitem_refresh=0x7f070034;
        public static final int defaultMeasureCheckBox=0x7f070022;
        public static final int displayinstances_menuitem_about=0x7f070039;
        public static final int displayinstances_menuitem_refresh=0x7f070038;
        public static final int durationSpinner=0x7f070021;
        public static final int durationTextView=0x7f070020;
        public static final int ec2DashboardRegionSpinner=0x7f070004;
        public static final int ec2DashboardTextView=0x7f070003;
        public static final int ec2DisplayInstancesTextView=0x7f070005;
        public static final int ec2SingleInstanceName=0x7f07000b;
        public static final int elasticIpsTextView=0x7f07000f;
        public static final int elasticips_menuitem_about=0x7f07003b;
        public static final int elasticips_menuitem_refresh=0x7f07003a;
        public static final int instanceData=0x7f07000e;
        public static final int instanceDetails=0x7f070007;
        public static final int instanceGroupDetails=0x7f07000a;
        public static final int instanceGroupHeadline=0x7f070009;
        public static final int instanceGroupsTitleTextView=0x7f070008;
        public static final int instanceHeadline=0x7f070006;
        public static final int instanceMetric=0x7f07000d;
        public static final int instanceStatusIcon=0x7f07000c;
        public static final int instancegroup_menuitem_save=0;
        public static final int ipDetails=0x7f070012;
        public static final int ipHeadline=0x7f070011;
        public static final int ipStatusIcon=0x7f070010;
        public static final int loginButton=0x7f07001b;
        public static final int loginTextView=0x7f070013;
        public static final int login_menuitem_about=0x7f07003d;
        public static final int login_menuitem_another_user=0x7f07003c;
        public static final int measureSpinner=0x7f07001f;
        public static final int measureTextView=0x7f07001e;
        public static final int monitorInstanceTextView=0x7f07001c;
        public static final int monitorinstance_menuitem_about=0x7f070041;
        public static final int monitorinstance_menuitem_graphtype=0x7f07003f;
        public static final int monitorinstance_menuitem_refresh=0x7f07003e;
        public static final int monitorinstance_menuitem_watch=0x7f070040;
        public static final int okButton=0x7f070030;
        public static final int portTextView=0x7f07002b;
        public static final int regionDropDownCheckedTextView=0x7f070001;
        public static final int regionTextView=0x7f070002;
        public static final int sakEntry=0x7f07001a;
        public static final int sakTextView=0x7f070019;
        public static final int securityGroupDescription=0x7f070025;
        public static final int securityGroupName=0x7f070024;
        public static final int securityGroupsTextView=0x7f070026;
        public static final int securitygroups_menuitem_about=0x7f070043;
        public static final int securitygroups_menuitem_refresh=0x7f070042;
        public static final int singleinstance_menuitem_about=0x7f07004a;
        public static final int singleinstance_menuitem_altersecgroup=0x7f070049;
        public static final int singleinstance_menuitem_controlinstance=0x7f070047;
        public static final int singleinstance_menuitem_monitor=0x7f070046;
        public static final int singleinstance_menuitem_refresh=0x7f070044;
        public static final int singleinstance_menuitem_ssh=0x7f070045;
        public static final int singleinstance_menuitem_tag=0x7f070048;
        public static final int sshConnectorLoginButton=0x7f07002e;
        public static final int sshConnectorPortSpinner=0x7f07002c;
        public static final int sshConnectorTitle=0x7f070028;
        public static final int sshConnectorUsePublicKeyAuth=0x7f07002d;
        public static final int sshConnectorUsernameEditTextView=0x7f07002a;
        public static final int sshConnectorUsernameTextView=0x7f070029;
        public static final int tagEntry=0x7f07002f;
        public static final int userPickerTextView=0x7f070031;
        public static final int username=0x7f070033;
        public static final int usernameEntry=0x7f070016;
        public static final int usernameTextView=0x7f070015;
        public static final int username_icon=0x7f070032;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int customspinnerdropdownitem=0x7f030001;
        public static final int customspinneritem=0x7f030002;
        public static final int defaultregion=0x7f030003;
        public static final int ec2dashboard=0x7f030004;
        public static final int ec2displayinstances=0x7f030005;
        public static final int ec2displayinstancesrow=0x7f030006;
        public static final int ec2instancegroups=0x7f030007;
        public static final int ec2instancegroupsrow=0x7f030008;
        public static final int ec2singleinstance=0x7f030009;
        public static final int ec2singleinstancerow=0x7f03000a;
        public static final int elasticips=0x7f03000b;
        public static final int elasticipsrow=0x7f03000c;
        public static final int instancegroupedit=0x7f03000d;
        public static final int login=0x7f03000e;
        public static final int monitorinstance=0x7f03000f;
        public static final int monitorinstanceoptions=0x7f030010;
        public static final int securitygrouprow=0x7f030011;
        public static final int securitygroups=0x7f030012;
        public static final int selectableinstancerow=0x7f030013;
        public static final int sshconnector=0x7f030014;
        public static final int tag=0x7f030015;
        public static final int userpicker=0x7f030016;
        public static final int userpickerrow=0x7f030017;
    }
    public static final class menu {
        public static final int dashboard_menu=0x7f060000;
        public static final int displayinstances_menu=0x7f060001;
        public static final int elasticips_menu=0x7f060002;
        public static final int login_menu=0x7f060003;
        public static final int monitorinstance_menu=0x7f060004;
        public static final int securitygroups_menu=0x7f060005;
        public static final int singleinstance_menu=0x7f060006;
        public static final int instancegroup_menu=0;

    }
    public static final class string {
        public static final int about_text=0x7f040070;
        public static final int about_titletext=0x7f04006f;
        public static final int app_name=0x7f04006d;
        public static final int app_version=0x7f04006e;
        public static final int cancelled=0x7f040073;
        /**   Cancelled message for when u need to click on the login button to retry 
  Cancelled message for when u need to click on the login button to retry 
  Cancelled message for when u need to click on the login button to retry 
         */
        public static final int cancelled_login=0x7f040074;
        public static final int connectbot_not_installed=0x7f04006c;
        public static final int dashboard_menu_default_region=0x7f04000a;
        public static final int ec2dashview_elasticip=0x7f040005;
        public static final int ec2dashview_illegal_arg_exception=0x7f040008;
        public static final int ec2dashview_instancegroups=0x7f040002;
        public static final int ec2dashview_keypairs=0x7f040007;
        public static final int ec2dashview_region=0x7f040009;
        public static final int ec2dashview_runninginstances=0x7f040003;
        public static final int ec2dashview_securitygroups=0x7f040006;
        public static final int ec2dashview_stoppedinstances=0x7f040004;
        public static final int ec2dashview_title=0x7f040001;
        public static final int ec2displayinstances_instanceID=0x7f04000e;
        /**   To translate 
  Translate 
         */
        public static final int ec2displayinstances_menu_no_instances=0x7f040013;
        public static final int ec2displayinstances_menu_refresh=0x7f040014;
        public static final int ec2displayinstances_os=0x7f040010;
        public static final int ec2displayinstances_rundays=0x7f040011;
        public static final int ec2displayinstances_runhrs=0x7f040012;
        public static final int ec2displayinstances_running_title=0x7f04000b;
        public static final int ec2displayinstances_stopped_title=0x7f04000c;
        public static final int ec2displayinstances_tag=0x7f04000d;
        public static final int ec2displayinstances_type=0x7f04000f;
        public static final int ec2instancegroupsview_edit=0x7f04001a;
        public static final int ec2instancegroupsview_groupname=0x7f040017;
        public static final int ec2instancegroupsview_input=0x7f04001d;
        public static final int ec2instancegroupsview_instances=0x7f040018;
        public static final int ec2instancegroupsview_new_group_notification=0x7f04001b;
        public static final int ec2instancegroupsview_new_instance_groups=0x7f040016;
        public static final int ec2instancegroupsview_save=0x7f040019;
        public static final int ec2instancegroupsview_select_instance=0x7f04001c;
        public static final int ec2instancegroupsview_title=0x7f040015;
        public static final int ec2singleinstance_ami=0x7f040029;
        public static final int ec2singleinstance_cannotcontrol=0x7f04002f;
        public static final int ec2singleinstance_elastic_ip=0x7f040027;
        public static final int ec2singleinstance_keypair=0x7f040025;
        public static final int ec2singleinstance_launchdetails_days=0x7f040023;
        public static final int ec2singleinstance_launchdetails_hrs=0x7f040024;
        public static final int ec2singleinstance_launchtime=0x7f040022;
        public static final int ec2singleinstance_menu_modifysecgroup=0x7f04002d;
        public static final int ec2singleinstance_menu_monitor=0x7f04002a;
        public static final int ec2singleinstance_menu_ssh=0x7f04002e;
        public static final int ec2singleinstance_menu_startinstance=0x7f04002c;
        public static final int ec2singleinstance_menu_stopinstance=0x7f04002b;
        public static final int ec2singleinstance_menu_tag=0x7f040031;
        public static final int ec2singleinstance_nopublicdns=0x7f040030;
        public static final int ec2singleinstance_os=0x7f040021;
        public static final int ec2singleinstance_public_ip=0x7f040028;
        public static final int ec2singleinstance_secgroup=0x7f040026;
        public static final int ec2singleinstance_state=0x7f04001f;
        public static final int ec2singleinstance_tag=0x7f04001e;
        public static final int ec2singleinstance_type=0x7f040020;
        public static final int elasticips_instanceID=0x7f040033;
        public static final int elasticips_title=0x7f040032;
        public static final int elasticips_unassociated=0x7f040034;
        public static final int loginview_accesskey_empty_err=0x7f04003c;
        public static final int loginview_alertdialogbox_button=0x7f04003a;
        public static final int loginview_aws_accesskey_textview=0x7f040037;
        public static final int loginview_aws_login_button=0x7f040039;
        public static final int loginview_aws_login_textview=0x7f040035;
        public static final int loginview_aws_secretAccessKey_textview=0x7f040038;
        public static final int loginview_aws_username_textview=0x7f040036;
        public static final int loginview_bug_report_dlg=0x7f040042;
        public static final int loginview_invalid_credentials_err=0x7f04003e;
        public static final int loginview_invalid_keys_dlg=0x7f04003f;
        public static final int loginview_invalid_username_err=0x7f040044;
        public static final int loginview_no_connxn_dlg=0x7f040043;
        public static final int loginview_secretaccesskey_empty_err=0x7f04003d;
        public static final int loginview_server_err_dlg=0x7f040040;
        public static final int loginview_switch_user=0x7f040046;
        public static final int loginview_unexpected_err_dlg=0x7f040041;
        public static final int loginview_username_empty_err=0x7f04003b;
        public static final int loginview_username_exists_dlg=0x7f040045;
        public static final int monitorinstanceview_cannotsave=0x7f040050;
        public static final int monitorinstanceview_change=0x7f04004b;
        public static final int monitorinstanceview_default=0x7f04004d;
        public static final int monitorinstanceview_duration=0x7f040049;
        public static final int monitorinstanceview_graphtype=0x7f040047;
        public static final int monitorinstanceview_interval=0x7f04004a;
        public static final int monitorinstanceview_measure=0x7f040048;
        public static final int monitorinstanceview_nodata=0x7f04004c;
        public static final int monitorinstanceview_nomeasures=0x7f040051;
        public static final int monitorinstanceview_watch=0x7f04004e;
        public static final int monitorinstanceview_watch_alert=0x7f04004f;
        /**   config stuff 
         */
        public static final int monitorinstancewidget_config_title=0x7f040054;
        public static final int monitorinstancewidget_configcanceled=0x7f040053;
        public static final int monitorinstancewidget_durationspinner=0x7f040059;
        public static final int monitorinstancewidget_instancespinner=0x7f040057;
        public static final int monitorinstancewidget_measurespinner=0x7f040058;
        /**  error messages 
         */
        public static final int monitorinstancewidget_nousers=0x7f04005b;
        public static final int monitorinstancewidget_nowatchedinstances=0x7f04005c;
        public static final int monitorinstancewidget_regionspinner=0x7f040056;
        public static final int monitorinstancewidget_saveconfig=0x7f04005a;
        public static final int monitorinstancewidget_title=0x7f040052;
        public static final int monitorinstancewidget_usernamespinner=0x7f040055;
        public static final int pick_from_sdcard=0x7f04006b;
        public static final int refresh=0x7f040071;
        public static final int regionsview_title=0x7f04005d;
        public static final int sdcard_absent=0x7f04006a;
        public static final int securityGroups_no_open_ports=0x7f040060;
        public static final int securityGroups_open_ports=0x7f04005f;
        public static final int securityGroups_title=0x7f04005e;
        public static final int ssh_defaultuser=0x7f040000;
        public static final int sshconnector_avail_ports=0x7f040065;
        public static final int sshconnector_cannotretrievehostip=0x7f040066;
        public static final int sshconnector_ipaddressblocked=0x7f040067;
        public static final int sshconnector_pickkey=0x7f040069;
        public static final int sshconnector_port=0x7f040063;
        public static final int sshconnector_portblocked=0x7f040068;
        public static final int sshconnector_publickey=0x7f040064;
        public static final int sshconnector_title=0x7f040061;
        public static final int sshconnector_username=0x7f040062;
        public static final int userpickerview_choose_login=0x7f040075;
        public static final int userpickerview_new_user=0x7f040076;
        public static final int wait_dlg=0x7f040072;
    }
}
