using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using java.applet;
using ScriptCoreLib;
using ScriptCoreLib.ActionScript;
using ScriptCoreLib.ActionScript.flash.display;
using ScriptCoreLib.JavaScript.DOM.HTML;
using ScriptCoreLib.JavaScript.Extensions;
using ScriptCoreLib.JavaScript;
using ScriptCoreLib.ActionScript.Extensions;
using java.awt;
using ScriptCoreLib.JavaScript.DOM;
using System.ComponentModel;
using ScriptCoreLib.ActionScript.flash.system;
using ScriptCoreLib.ActionScript.flash.external;

namespace Ultra3
{






	[ScriptApplicationEntryPoint]
	[Description("OrcasClientScriptApplication. Write javascript, flash and java applets within a C# project.")]
	public class UltraApplication
	{


		// possible names:
		// 1. application
		// 2. document
		// 3. element
		// 4. control



		public UltraApplication(IHTMLElement e)
		{
			// we are attaching to the DOM now after onload event
			// bootstrap code was generated by jsc.meta and is using ScriptCoreLib

			new IHTMLDiv
			{
				innerText = "javascript to flash does not work in IE"
			}.ToWarningColor().AttachToDocument();

			new IHTMLDiv
			{
				innerText = "flash needs to run from http://"
			}.ToWarningColor().AttachToDocument();

			new IHTMLDiv
			{
				innerText = "Create sprite, add event, raise event, click on color"
			}.AttachToDocument();

			#region UltraSprite javascript to flash
			{
				var x = new IHTMLButton("create UltraSprite javascript to flash");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{
						var o = new UltraSprite();

						o.AttachToDocument();

						var f4 = new IHTMLButton("UltraSprite.raise_event1");

						f4.onclick +=
							delegate
							{

								o.raise_event1();
								o.RaiseAction2("q", "w");
							};

						// how we get it:
						var f3 = new IHTMLButton("UltraSprite.add_event1");

						f3.onclick +=
							delegate
							{

								o.event1 +=
									delegate
									{
										new IHTMLDiv { innerText = "got event1! " + o.status1 }.AttachToDocument();
									};

								o.AtAction1 +=
									(xx, y) =>
									{
										new IHTMLDiv { innerText = "x: " + xx + ", y:" + y }.AttachToDocument();
									};
							};

						var f2 = new IHTMLButton("UltraSprite.FunctionTwo");

						f2.onclick +=
							delegate
							{
								o.FunctionTwo("hi from js");
							};

						f4.AttachToDocument();
						f2.AttachToDocument();
						f3.AttachToDocument();
					};
			}
			#endregion


			{
				var x = new IHTMLButton("create UltraApplet proxied");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{
						var o = new UltraApplet();

						o.AttachToDocument();
					};
			}


		}


	}
}
