//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertASToCS.Any.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Adobe® Flex™ 3 Language Reference\t\r\n\tAll Packages | All Classes | Language Elemen" +
            "ts | Index\r\n | Appendixes | Conventions | Frames No Frames \tAdobe Logo\r\nKeyboard" +
            "\tProperties | Methods | Constants\r\n \r\nPackage\tflash.ui\r\nClass\tpublic final class" +
            " Keyboard\r\nInheritance\tKeyboard Inheritance Object\r\n\r\nThe Keyboard class is used" +
            " to build an interface that can be controlled by a user with a standard keyboard" +
            ". You can use the methods and properties of the Keyboard class without using a c" +
            "onstructor. The properties of the Keyboard class are constants representing the " +
            "keys that are most commonly used to control games. <Updated May 12, 2008 - added" +
            " \"AIR Only\" icons for constants that are only available in Adobe AIR>\r\n\r\nSee als" +
            "o\r\nCapturing keyboard input\r\n\r\nPublic Properties\r\nHide Inherited Public Properti" +
            "es\r\nShow Inherited Public Properties\r\n \tProperty\tDefined By\r\n \t \tcapsLock : Bool" +
            "ean\r\n[static] [read-only] Specifies whether the Caps Lock key is activated (true" +
            ") or not (false).\r\n\tKeyboard\r\n \tInherited\tconstructor : Object\r\nA reference to t" +
            "he class object or constructor function for a given object instance.\r\n\tObject\r\n " +
            "\t \tnumLock : Boolean\r\n[static] [read-only] Specifies whether the Num Lock key is" +
            " activated (true) or not (false).\r\n\tKeyboard\r\n \tInherited\tprototype : Object\r\n[s" +
            "tatic] A reference to the prototype object of a class or function object.\r\n\tObje" +
            "ct\r\nPublic Methods\r\nHide Inherited Public Methods\r\nShow Inherited Public Methods" +
            "\r\n \tMethod\tDefined By\r\n \tInherited\t\r\nhasOwnProperty(name:String):Boolean\r\nIndica" +
            "tes whether an object has a specified property defined.\r\n\tObject\r\n \t \t\r\nisAccess" +
            "ible():Boolean\r\n[static] Specifies whether the last key pressed is accessible by" +
            " other SWF files.\r\n\tKeyboard\r\n \tInherited\t\r\nisPrototypeOf(theClass:Object):Boole" +
            "an\r\nIndicates whether an instance of the Object class is in the prototype chain " +
            "of the object specified as the parameter.\r\n\tObject\r\n \tInherited\t\r\npropertyIsEnum" +
            "erable(name:String):Boolean\r\nIndicates whether the specified property exists and" +
            " is enumerable.\r\n\tObject\r\n \tInherited\t\r\nsetPropertyIsEnumerable(name:String, isE" +
            "num:Boolean = true):void\r\nSets the availability of a dynamic property for loop o" +
            "perations.\r\n\tObject\r\n \tInherited\t\r\ntoString():String\r\nReturns the string represe" +
            "ntation of the specified object.\r\n\tObject\r\n \tInherited\t\r\nvalueOf():Object\r\nRetur" +
            "ns the primitive value of the specified object.\r\n\tObject\r\nPublic Constants\r\n \tCo" +
            "nstant\tDefined By\r\n \t \tAIR-only A : uint = 65\r\n[static] Constant associated with" +
            " the key code value for the A key (65).\r\n\tKeyboard\r\n \t \tAIR-only ALTERNATE : uin" +
            "t = 18\r\n[static] Constant associated with the key code value for the Alternate (" +
            "Option) key (18).\r\n\tKeyboard\r\n \t \tAIR-only B : uint = 66\r\n[static] Constant asso" +
            "ciated with the key code value for the B key (66).\r\n\tKeyboard\r\n \t \tAIR-only BACK" +
            "QUOTE : uint = 192\r\n[static] Constant associated with the key code value for the" +
            " ` key (192).\r\n\tKeyboard\r\n \t \tAIR-only BACKSLASH : uint = 220\r\n[static] Constant" +
            " associated with the key code value for the \\ key (220).\r\n\tKeyboard\r\n \t \tBACKSPA" +
            "CE : uint = 8\r\n[static] Constant associated with the key code value for the Back" +
            "space key (8).\r\n\tKeyboard\r\n \t \tAIR-only C : uint = 67\r\n[static] Constant associa" +
            "ted with the key code value for the C key (67).\r\n\tKeyboard\r\n \t \tCAPS_LOCK : uint" +
            " = 20\r\n[static] Constant associated with the key code value for the Caps Lock ke" +
            "y (20).\r\n\tKeyboard\r\n \t \tAIR-only CharCodeStrings : Array\r\n[static]\r\n\tKeyboard\r\n " +
            "\t \tAIR-only COMMA : uint = 188\r\n[static] Constant associated with the key code v" +
            "alue for the , key (188).\r\n\tKeyboard\r\n \t \tAIR-only COMMAND : uint = 15\r\n[static]" +
            " Constant associated with the Mac command key (15).\r\n\tKeyboard\r\n \t \tCONTROL : ui" +
            "nt = 17\r\n[static] Constant associated with the key code value for the Control ke" +
            "y (17).\r\n\tKeyboard\r\n \t \tAIR-only D : uint = 68\r\n[static] Constant associated wit" +
            "h the key code value for the D key (68).\r\n\tKeyboard\r\n \t \tDELETE : uint = 46\r\n[st" +
            "atic] Constant associated with the key code value for the Delete key (46).\r\n\tKey" +
            "board\r\n \t \tDOWN : uint = 40\r\n[static] Constant associated with the key code valu" +
            "e for the Down Arrow key (40).\r\n\tKeyboard\r\n \t \tAIR-only E : uint = 69\r\n[static] " +
            "Constant associated with the key code value for the E key (69).\r\n\tKeyboard\r\n \t \t" +
            "END : uint = 35\r\n[static] Constant associated with the key code value for the En" +
            "d key (35).\r\n\tKeyboard\r\n \t \tENTER : uint = 13\r\n[static] Constant associated with" +
            " the key code value for the Enter key (13).\r\n\tKeyboard\r\n \t \tAIR-only EQUAL : uin" +
            "t = 187\r\n[static] Constant associated with the key code value for the = key (187" +
            ").\r\n\tKeyboard\r\n \t \tESCAPE : uint = 27\r\n[static] Constant associated with the key" +
            " code value for the Escape key (27).\r\n\tKeyboard\r\n \t \tAIR-only F : uint = 70\r\n[st" +
            "atic] Constant associated with the key code value for the F key (70).\r\n\tKeyboard" +
            "\r\n \t \tF1 : uint = 112\r\n[static] Constant associated with the key code value for " +
            "the F1 key (112).\r\n\tKeyboard\r\n \t \tF10 : uint = 121\r\n[static] Constant associated" +
            " with the key code value for the F10 key (121).\r\n\tKeyboard\r\n \t \tF11 : uint = 122" +
            "\r\n[static] Constant associated with the key code value for the F11 key (122).\r\n\t" +
            "Keyboard\r\n \t \tF12 : uint = 123\r\n[static] Constant associated with the key code v" +
            "alue for the F12 key (123).\r\n\tKeyboard\r\n \t \tF13 : uint = 124\r\n[static] Constant " +
            "associated with the key code value for the F13 key (124).\r\n\tKeyboard\r\n \t \tF14 : " +
            "uint = 125\r\n[static] Constant associated with the key code value for the F14 key" +
            " (125).\r\n\tKeyboard\r\n \t \tF15 : uint = 126\r\n[static] Constant associated with the " +
            "key code value for the F15 key (126).\r\n\tKeyboard\r\n \t \tF2 : uint = 113\r\n[static] " +
            "Constant associated with the key code value for the F2 key (113).\r\n\tKeyboard\r\n \t" +
            " \tF3 : uint = 114\r\n[static] Constant associated with the key code value for the " +
            "F3 key (114).\r\n\tKeyboard\r\n \t \tF4 : uint = 115\r\n[static] Constant associated with" +
            " the key code value for the F4 key (115).\r\n\tKeyboard\r\n \t \tF5 : uint = 116\r\n[stat" +
            "ic] Constant associated with the key code value for the F5 key (116).\r\n\tKeyboard" +
            "\r\n \t \tF6 : uint = 117\r\n[static] Constant associated with the key code value for " +
            "the F6 key (117).\r\n\tKeyboard\r\n \t \tF7 : uint = 118\r\n[static] Constant associated " +
            "with the key code value for the F7 key (118).\r\n\tKeyboard\r\n \t \tF8 : uint = 119\r\n[" +
            "static] Constant associated with the key code value for the F8 key (119).\r\n\tKeyb" +
            "oard\r\n \t \tF9 : uint = 120\r\n[static] Constant associated with the key code value " +
            "for the F9 key (120).\r\n\tKeyboard\r\n \t \tAIR-only G : uint = 71\r\n[static] Constant " +
            "associated with the key code value for the G key (71).\r\n\tKeyboard\r\n \t \tAIR-only " +
            "H : uint = 72\r\n[static] Constant associated with the key code value for the H ke" +
            "y (72).\r\n\tKeyboard\r\n \t \tHOME : uint = 36\r\n[static] Constant associated with the " +
            "key code value for the Home key (36).\r\n\tKeyboard\r\n \t \tAIR-only I : uint = 73\r\n[s" +
            "tatic] Constant associated with the key code value for the I key (73).\r\n\tKeyboar" +
            "d\r\n \t \tINSERT : uint = 45\r\n[static] Constant associated with the key code value " +
            "for the Insert key (45).\r\n\tKeyboard\r\n \t \tAIR-only J : uint = 74\r\n[static] Consta" +
            "nt associated with the key code value for the J key (74).\r\n\tKeyboard\r\n \t \tAIR-on" +
            "ly K : uint = 75\r\n[static] Constant associated with the key code value for the K" +
            " key (75).\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_BEGIN : String = \"Begin\"\r\n[static]\r\n" +
            "\tKeyboard\r\n \t \tAIR-only KEYNAME_BREAK : String = \"Break\"\r\n[static]\r\n\tKeyboard\r\n " +
            "\t \tAIR-only KEYNAME_CLEARDISPLAY : String = \"ClrDsp\"\r\n[static]\r\n\tKeyboard\r\n \t \tA" +
            "IR-only KEYNAME_CLEARLINE : String = \"ClrLn\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only " +
            "KEYNAME_DELETE : String = \"Delete\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_DE" +
            "LETECHAR : String = \"DelChr\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_DELETELI" +
            "NE : String = \"DelLn\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_DOWNARROW : Str" +
            "ing = \"Down\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_END : String = \"End\"\r\n[s" +
            "tatic]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_EXECUTE : String = \"Exec\"\r\n[static]\r\n\tKe" +
            "yboard\r\n \t \tAIR-only KEYNAME_F1 : String = \"F1\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-on" +
            "ly KEYNAME_F10 : String = \"F10\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F11 :" +
            " String = \"F11\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F12 : String = \"F12\"\r" +
            "\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F13 : String = \"F13\"\r\n[static]\r\n\tKeyb" +
            "oard\r\n \t \tAIR-only KEYNAME_F14 : String = \"F14\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-on" +
            "ly KEYNAME_F15 : String = \"F15\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F16 :" +
            " String = \"F16\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F17 : String = \"F17\"\r" +
            "\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F18 : String = \"F18\"\r\n[static]\r\n\tKeyb" +
            "oard\r\n \t \tAIR-only KEYNAME_F19 : String = \"F19\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-on" +
            "ly KEYNAME_F2 : String = \"F2\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F20 : S" +
            "tring = \"F20\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F21 : String = \"F21\"\r\n[" +
            "static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F22 : String = \"F22\"\r\n[static]\r\n\tKeyboa" +
            "rd\r\n \t \tAIR-only KEYNAME_F23 : String = \"F23\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only" +
            " KEYNAME_F24 : String = \"F24\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F25 : S" +
            "tring = \"F25\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F26 : String = \"F26\"\r\n[" +
            "static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F27 : String = \"F27\"\r\n[static]\r\n\tKeyboa" +
            "rd\r\n \t \tAIR-only KEYNAME_F28 : String = \"F28\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only" +
            " KEYNAME_F29 : String = \"F29\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F3 : St" +
            "ring = \"F3\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F30 : String = \"F30\"\r\n[st" +
            "atic]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F31 : String = \"F31\"\r\n[static]\r\n\tKeyboard" +
            "\r\n \t \tAIR-only KEYNAME_F32 : String = \"F32\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only K" +
            "EYNAME_F33 : String = \"F33\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F34 : Str" +
            "ing = \"F34\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F35 : String = \"F35\"\r\n[st" +
            "atic]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F4 : String = \"F4\"\r\n[static]\r\n\tKeyboard\r\n" +
            " \t \tAIR-only KEYNAME_F5 : String = \"F5\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNA" +
            "ME_F6 : String = \"F6\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F7 : String = \"" +
            "F7\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_F8 : String = \"F8\"\r\n[static]\r\n\tKe" +
            "yboard\r\n \t \tAIR-only KEYNAME_F9 : String = \"F9\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-on" +
            "ly KEYNAME_FIND : String = \"Find\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_HEL" +
            "P : String = \"Help\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_HOME : String = \"" +
            "Home\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_INSERT : String = \"Insert\"\r\n[st" +
            "atic]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_INSERTCHAR : String = \"InsChr\"\r\n[static]\r" +
            "\n\tKeyboard\r\n \t \tAIR-only KEYNAME_INSERTLINE : String = \"InsLn\"\r\n[static]\r\n\tKeybo" +
            "ard\r\n \t \tAIR-only KEYNAME_LEFTARROW : String = \"Left\"\r\n[static]\r\n\tKeyboard\r\n \t \t" +
            "AIR-only KEYNAME_MENU : String = \"Menu\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNA" +
            "ME_MODESWITCH : String = \"ModeSw\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_NEX" +
            "T : String = \"Next\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_PAGEDOWN : String" +
            " = \"PgDn\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_PAGEUP : String = \"PgUp\"\r\n[" +
            "static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_PAUSE : String = \"Pause\"\r\n[static]\r\n\tKe" +
            "yboard\r\n \t \tAIR-only KEYNAME_PREV : String = \"Prev\"\r\n[static]\r\n\tKeyboard\r\n \t \tAI" +
            "R-only KEYNAME_PRINT : String = \"Print\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNA" +
            "ME_PRINTSCREEN : String = \"PrntScrn\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_" +
            "REDO : String = \"Redo\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_RESET : String" +
            " = \"Reset\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_RIGHTARROW : String = \"Rig" +
            "ht\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_SCROLLLOCK : String = \"ScrlLck\"\r\n" +
            "[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_SELECT : String = \"Select\"\r\n[static]\r\n" +
            "\tKeyboard\r\n \t \tAIR-only KEYNAME_STOP : String = \"Stop\"\r\n[static]\r\n\tKeyboard\r\n \t " +
            "\tAIR-only KEYNAME_SYSREQ : String = \"SysReq\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only " +
            "KEYNAME_SYSTEM : String = \"Sys\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_UNDO " +
            ": String = \"Undo\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_UPARROW : String = " +
            "\"Up\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only KEYNAME_USER : String = \"User\"\r\n[static]" +
            "\r\n\tKeyboard\r\n \t \tAIR-only L : uint = 76\r\n[static] Constant associated with the k" +
            "ey code value for the L key (76).\r\n\tKeyboard\r\n \t \tLEFT : uint = 37\r\n[static] Con" +
            "stant associated with the key code value for the Left Arrow key (37).\r\n\tKeyboard" +
            "\r\n \t \tAIR-only LEFTBRACKET : uint = 219\r\n[static] Constant associated with the k" +
            "ey code value for the [ key (219).\r\n\tKeyboard\r\n \t \tAIR-only M : uint = 77\r\n[stat" +
            "ic] Constant associated with the key code value for the M key (77).\r\n\tKeyboard\r\n" +
            " \t \tAIR-only MINUS : uint = 189\r\n[static] Constant associated with the key code " +
            "value for the - key (189).\r\n\tKeyboard\r\n \t \tAIR-only N : uint = 78\r\n[static] Cons" +
            "tant associated with the key code value for the N key (78).\r\n\tKeyboard\r\n \t \tAIR-" +
            "only NUMBER_0 : uint = 48\r\n[static] Constant associated with the key code value " +
            "for the 0 key (48).\r\n\tKeyboard\r\n \t \tAIR-only NUMBER_1 : uint = 49\r\n[static] Cons" +
            "tant associated with the key code value for the 1 key (49).\r\n\tKeyboard\r\n \t \tAIR-" +
            "only NUMBER_2 : uint = 50\r\n[static] Constant associated with the key code value " +
            "for the 2 key (50).\r\n\tKeyboard\r\n \t \tAIR-only NUMBER_3 : uint = 51\r\n[static] Cons" +
            "tant associated with the key code value for the 3 key (51).\r\n\tKeyboard\r\n \t \tAIR-" +
            "only NUMBER_4 : uint = 52\r\n[static] Constant associated with the key code value " +
            "for the 4 key (52).\r\n\tKeyboard\r\n \t \tAIR-only NUMBER_5 : uint = 53\r\n[static] Cons" +
            "tant associated with the key code value for the 5 key (53).\r\n\tKeyboard\r\n \t \tAIR-" +
            "only NUMBER_6 : uint = 54\r\n[static] Constant associated with the key code value " +
            "for the 6 key (54).\r\n\tKeyboard\r\n \t \tAIR-only NUMBER_7 : uint = 55\r\n[static] Cons" +
            "tant associated with the key code value for the 7 key (55).\r\n\tKeyboard\r\n \t \tAIR-" +
            "only NUMBER_8 : uint = 56\r\n[static] Constant associated with the key code value " +
            "for the 8 key (56).\r\n\tKeyboard\r\n \t \tAIR-only NUMBER_9 : uint = 57\r\n[static] Cons" +
            "tant associated with the key code value for the 9 key (57).\r\n\tKeyboard\r\n \t \tAIR-" +
            "only NUMPAD : uint = 21\r\n[static] Constant associated with the pseudo-key code f" +
            "or the the number pad (21).\r\n\tKeyboard\r\n \t \tNUMPAD_0 : uint = 96\r\n[static] Const" +
            "ant associated with the key code value for the number 0 key on the number pad (9" +
            "6).\r\n\tKeyboard\r\n \t \tNUMPAD_1 : uint = 97\r\n[static] Constant associated with the " +
            "key code value for the number 1 key on the number pad (97).\r\n\tKeyboard\r\n \t \tNUMP" +
            "AD_2 : uint = 98\r\n[static] Constant associated with the key code value for the n" +
            "umber 2 key on the number pad (98).\r\n\tKeyboard\r\n \t \tNUMPAD_3 : uint = 99\r\n[stati" +
            "c] Constant associated with the key code value for the number 3 key on the numbe" +
            "r pad (99).\r\n\tKeyboard\r\n \t \tNUMPAD_4 : uint = 100\r\n[static] Constant associated " +
            "with the key code value for the number 4 key on the number pad (100).\r\n\tKeyboard" +
            "\r\n \t \tNUMPAD_5 : uint = 101\r\n[static] Constant associated with the key code valu" +
            "e for the number 5 key on the number pad (101).\r\n\tKeyboard\r\n \t \tNUMPAD_6 : uint " +
            "= 102\r\n[static] Constant associated with the key code value for the number 6 key" +
            " on the number pad (102).\r\n\tKeyboard\r\n \t \tNUMPAD_7 : uint = 103\r\n[static] Consta" +
            "nt associated with the key code value for the number 7 key on the number pad (10" +
            "3).\r\n\tKeyboard\r\n \t \tNUMPAD_8 : uint = 104\r\n[static] Constant associated with the" +
            " key code value for the number 8 key on the number pad (104).\r\n\tKeyboard\r\n \t \tNU" +
            "MPAD_9 : uint = 105\r\n[static] Constant associated with the key code value for th" +
            "e number 9 key on the number pad (105).\r\n\tKeyboard\r\n \t \tNUMPAD_ADD : uint = 107\r" +
            "\n[static] Constant associated with the key code value for the addition key on th" +
            "e number pad (107).\r\n\tKeyboard\r\n \t \tNUMPAD_DECIMAL : uint = 110\r\n[static] Consta" +
            "nt associated with the key code value for the decimal key on the number pad (110" +
            ").\r\n\tKeyboard\r\n \t \tNUMPAD_DIVIDE : uint = 111\r\n[static] Constant associated with" +
            " the key code value for the division key on the number pad (111).\r\n\tKeyboard\r\n \t" +
            " \tNUMPAD_ENTER : uint = 108\r\n[static] Constant associated with the key code valu" +
            "e for the Enter key on the number pad (108).\r\n\tKeyboard\r\n \t \tNUMPAD_MULTIPLY : u" +
            "int = 106\r\n[static] Constant associated with the key code value for the multipli" +
            "cation key on the number pad (106).\r\n\tKeyboard\r\n \t \tNUMPAD_SUBTRACT : uint = 109" +
            "\r\n[static] Constant associated with the key code value for the subtraction key o" +
            "n the number pad (109).\r\n\tKeyboard\r\n \t \tAIR-only O : uint = 79\r\n[static] Constan" +
            "t associated with the key code value for the O key (79).\r\n\tKeyboard\r\n \t \tAIR-onl" +
            "y P : uint = 80\r\n[static] Constant associated with the key code value for the P " +
            "key (80).\r\n\tKeyboard\r\n \t \tPAGE_DOWN : uint = 34\r\n[static] Constant associated wi" +
            "th the key code value for the Page Down key (34).\r\n\tKeyboard\r\n \t \tPAGE_UP : uint" +
            " = 33\r\n[static] Constant associated with the key code value for the Page Up key " +
            "(33).\r\n\tKeyboard\r\n \t \tAIR-only PERIOD : uint = 190\r\n[static] Constant associated" +
            " with the key code value for the .\r\n\tKeyboard\r\n \t \tAIR-only Q : uint = 81\r\n[stat" +
            "ic] Constant associated with the key code value for the Q key (81).\r\n\tKeyboard\r\n" +
            " \t \tAIR-only QUOTE : uint = 222\r\n[static] Constant associated with the key code " +
            "value for the \' key (222).\r\n\tKeyboard\r\n \t \tAIR-only R : uint = 82\r\n[static] Cons" +
            "tant associated with the key code value for the R key (82).\r\n\tKeyboard\r\n \t \tRIGH" +
            "T : uint = 39\r\n[static] Constant associated with the key code value for the Righ" +
            "t Arrow key (39).\r\n\tKeyboard\r\n \t \tAIR-only RIGHTBRACKET : uint = 221\r\n[static] C" +
            "onstant associated with the key code value for the ] key (221).\r\n\tKeyboard\r\n \t \t" +
            "AIR-only S : uint = 83\r\n[static] Constant associated with the key code value for" +
            " the S key (83).\r\n\tKeyboard\r\n \t \tAIR-only SEMICOLON : uint = 186\r\n[static] Const" +
            "ant associated with the key code value for the ; key (186).\r\n\tKeyboard\r\n \t \tSHIF" +
            "T : uint = 16\r\n[static] Constant associated with the key code value for the Shif" +
            "t key (16).\r\n\tKeyboard\r\n \t \tAIR-only SLASH : uint = 191\r\n[static] Constant assoc" +
            "iated with the key code value for the / key (191).\r\n\tKeyboard\r\n \t \tSPACE : uint " +
            "= 32\r\n[static] Constant associated with the key code value for the Spacebar (32)" +
            ".\r\n\tKeyboard\r\n \t \tAIR-only STRING_BEGIN : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t " +
            "\tAIR-only STRING_BREAK : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_" +
            "CLEARDISPLAY : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_CLEARLINE " +
            ": String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_DELETE : String = \"?\"\r\n" +
            "[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_DELETECHAR : String = \"?\"\r\n[static]\r\n\tK" +
            "eyboard\r\n \t \tAIR-only STRING_DELETELINE : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t " +
            "\tAIR-only STRING_DOWNARROW : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STR" +
            "ING_END : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_EXECUTE : Strin" +
            "g = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F1 : String = \"?\"\r\n[static]\r\n\t" +
            "Keyboard\r\n \t \tAIR-only STRING_F10 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-o" +
            "nly STRING_F11 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F12 : St" +
            "ring = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F13 : String = \"?\"\r\n[static" +
            "]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F14 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tA" +
            "IR-only STRING_F15 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F16 " +
            ": String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F17 : String = \"?\"\r\n[st" +
            "atic]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F18 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n " +
            "\t \tAIR-only STRING_F19 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_" +
            "F2 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F20 : String = \"?\"\r\n" +
            "[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F21 : String = \"?\"\r\n[static]\r\n\tKeyboard" +
            "\r\n \t \tAIR-only STRING_F22 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRI" +
            "NG_F23 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F24 : String = \"" +
            "?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F25 : String = \"?\"\r\n[static]\r\n\tKeyb" +
            "oard\r\n \t \tAIR-only STRING_F26 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only " +
            "STRING_F27 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F28 : String" +
            " = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F29 : String = \"?\"\r\n[static]\r\n\t" +
            "Keyboard\r\n \t \tAIR-only STRING_F3 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-on" +
            "ly STRING_F30 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F31 : Str" +
            "ing = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F32 : String = \"?\"\r\n[static]" +
            "\r\n\tKeyboard\r\n \t \tAIR-only STRING_F33 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAI" +
            "R-only STRING_F34 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F35 :" +
            " String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F4 : String = \"?\"\r\n[stat" +
            "ic]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F5 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \t" +
            "AIR-only STRING_F6 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F7 :" +
            " String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F8 : String = \"?\"\r\n[stat" +
            "ic]\r\n\tKeyboard\r\n \t \tAIR-only STRING_F9 : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \t" +
            "AIR-only STRING_FIND : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_HE" +
            "LP : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_HOME : String = \"?\"\r" +
            "\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_INSERT : String = \"?\"\r\n[static]\r\n\tKeyb" +
            "oard\r\n \t \tAIR-only STRING_INSERTCHAR : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAI" +
            "R-only STRING_INSERTLINE : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRIN" +
            "G_LEFTARROW : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_MENU : Stri" +
            "ng = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_MODESWITCH : String = \"?\"\r\n[s" +
            "tatic]\r\n\tKeyboard\r\n \t \tAIR-only STRING_NEXT : String = \"?\"\r\n[static]\r\n\tKeyboard\r" +
            "\n \t \tAIR-only STRING_PAGEDOWN : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only " +
            "STRING_PAGEUP : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_PAUSE : S" +
            "tring = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_PREV : String = \"?\"\r\n[stat" +
            "ic]\r\n\tKeyboard\r\n \t \tAIR-only STRING_PRINT : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n " +
            "\t \tAIR-only STRING_PRINTSCREEN : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only" +
            " STRING_REDO : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_RESET : St" +
            "ring = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_RIGHTARROW : String = \"?\"\r\n" +
            "[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_SCROLLLOCK : String = \"?\"\r\n[static]\r\n\tK" +
            "eyboard\r\n \t \tAIR-only STRING_SELECT : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR" +
            "-only STRING_STOP : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_SYSRE" +
            "Q : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_SYSTEM : String = \"?\"" +
            "\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only STRING_UNDO : String = \"?\"\r\n[static]\r\n\tKeybo" +
            "ard\r\n \t \tAIR-only STRING_UPARROW : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-on" +
            "ly STRING_USER : String = \"?\"\r\n[static]\r\n\tKeyboard\r\n \t \tAIR-only T : uint = 84\r\n" +
            "[static] Constant associated with the key code value for the T key (84).\r\n\tKeybo" +
            "ard\r\n \t \tTAB : uint = 9\r\n[static] Constant associated with the key code value fo" +
            "r the Tab key (9).\r\n\tKeyboard\r\n \t \tAIR-only U : uint = 85\r\n[static] Constant ass" +
            "ociated with the key code value for the U key (85).\r\n\tKeyboard\r\n \t \tUP : uint = " +
            "38\r\n[static] Constant associated with the key code value for the Up Arrow key (3" +
            "8).\r\n\tKeyboard\r\n \t \tAIR-only V : uint = 86\r\n[static] Constant associated with th" +
            "e key code value for the V key (86).\r\n\tKeyboard\r\n \t \tAIR-only W : uint = 87\r\n[st" +
            "atic] Constant associated with the key code value for the W key (87).\r\n\tKeyboard" +
            "\r\n \t \tAIR-only X : uint = 88\r\n[static] Constant associated with the key code val" +
            "ue for the X key (88).\r\n\tKeyboard\r\n \t \tAIR-only Y : uint = 89\r\n[static] Constant" +
            " associated with the key code value for the Y key (89).\r\n\tKeyboard\r\n \t \tAIR-only" +
            " Z : uint = 90\r\n[static] Constant associated with the key code value for the Z k" +
            "ey (90).\r\n\tKeyboard\r\nProperty Detail\r\ncapsLock\tproperty\r\ncapsLock:Boolean  [read" +
            "-only]\r\n\r\nSpecifies whether the Caps Lock key is activated (true) or not (false)" +
            ".\r\n\r\nImplementation\r\n    public static function get capsLock():Boolean\r\nnumLock\t" +
            "property\t \r\nnumLock:Boolean  [read-only]\r\n\r\nSpecifies whether the Num Lock key i" +
            "s activated (true) or not (false).\r\n\r\nImplementation\r\n    public static function" +
            " get numLock():Boolean\r\nMethod Detail\r\nisAccessible\t()\tmethod\r\npublic static fun" +
            "ction isAccessible():Boolean\r\n\r\nSpecifies whether the last key pressed is access" +
            "ible by other SWF files. By default, security restrictions prevent code from a S" +
            "WF file in one domain from accessing a keystroke generated from a SWF file in an" +
            "other domain.\r\n\r\nReturns\r\n\tBoolean — The value true if the last key pressed can " +
            "be accessed. If access is not permitted, this method returns false.\r\nConstant De" +
            "tail\r\nAIR-only A\tConstant\r\npublic static const A:uint = 65\r\n\r\nConstant associate" +
            "d with the key code value for the A key (65).\r\nAIR-only ALTERNATE\tConstant\t \r\npu" +
            "blic static const ALTERNATE:uint = 18\r\n\r\nConstant associated with the key code v" +
            "alue for the Alternate (Option) key (18).\r\nAIR-only B\tConstant\t \r\npublic static " +
            "const B:uint = 66\r\n\r\nConstant associated with the key code value for the B key (" +
            "66).\r\nAIR-only BACKQUOTE\tConstant\t \r\npublic static const BACKQUOTE:uint = 192\r\n\r" +
            "\nConstant associated with the key code value for the ` key (192).\r\nAIR-only BACK" +
            "SLASH\tConstant\t \r\npublic static const BACKSLASH:uint = 220\r\n\r\nConstant associate" +
            "d with the key code value for the \\ key (220).\r\nBACKSPACE\tConstant\t \r\npublic sta" +
            "tic const BACKSPACE:uint = 8\r\n\r\nConstant associated with the key code value for " +
            "the Backspace key (8).\r\nAIR-only C\tConstant\t \r\npublic static const C:uint = 67\r\n" +
            "\r\nConstant associated with the key code value for the C key (67).\r\nCAPS_LOCK\tCon" +
            "stant\t \r\npublic static const CAPS_LOCK:uint = 20\r\n\r\nConstant associated with the" +
            " key code value for the Caps Lock key (20).\r\nAIR-only CharCodeStrings\tConstant\t " +
            "\r\npublic static const CharCodeStrings:Array\r\nAIR-only COMMA\tConstant\t \r\npublic s" +
            "tatic const COMMA:uint = 188\r\n\r\nConstant associated with the key code value for " +
            "the , key (188).\r\nAIR-only COMMAND\tConstant\t \r\npublic static const COMMAND:uint " +
            "= 15\r\n\r\nConstant associated with the Mac command key (15). This constant is curr" +
            "ently only used for setting menu key equivalents.\r\nCONTROL\tConstant\t \r\npublic st" +
            "atic const CONTROL:uint = 17\r\n\r\nConstant associated with the key code value for " +
            "the Control key (17).\r\nAIR-only D\tConstant\t \r\npublic static const D:uint = 68\r\n\r" +
            "\nConstant associated with the key code value for the D key (68).\r\nDELETE\tConstan" +
            "t\t \r\npublic static const DELETE:uint = 46\r\n\r\nConstant associated with the key co" +
            "de value for the Delete key (46).\r\nDOWN\tConstant\t \r\npublic static const DOWN:uin" +
            "t = 40\r\n\r\nConstant associated with the key code value for the Down Arrow key (40" +
            ").\r\nAIR-only E\tConstant\t \r\npublic static const E:uint = 69\r\n\r\nConstant associate" +
            "d with the key code value for the E key (69).\r\nEND\tConstant\t \r\npublic static con" +
            "st END:uint = 35\r\n\r\nConstant associated with the key code value for the End key " +
            "(35).\r\nENTER\tConstant\t \r\npublic static const ENTER:uint = 13\r\n\r\nConstant associa" +
            "ted with the key code value for the Enter key (13).\r\nAIR-only EQUAL\tConstant\t \r\n" +
            "public static const EQUAL:uint = 187\r\n\r\nConstant associated with the key code va" +
            "lue for the = key (187).\r\nESCAPE\tConstant\t \r\npublic static const ESCAPE:uint = 2" +
            "7\r\n\r\nConstant associated with the key code value for the Escape key (27).\r\nAIR-o" +
            "nly F\tConstant\t \r\npublic static const F:uint = 70\r\n\r\nConstant associated with th" +
            "e key code value for the F key (70).\r\nF1\tConstant\t \r\npublic static const F1:uint" +
            " = 112\r\n\r\nConstant associated with the key code value for the F1 key (112).\r\nF10" +
            "\tConstant\t \r\npublic static const F10:uint = 121\r\n\r\nConstant associated with the " +
            "key code value for the F10 key (121).\r\nF11\tConstant\t \r\npublic static const F11:u" +
            "int = 122\r\n\r\nConstant associated with the key code value for the F11 key (122).\r" +
            "\nF12\tConstant\t \r\npublic static const F12:uint = 123\r\n\r\nConstant associated with " +
            "the key code value for the F12 key (123).\r\nF13\tConstant\t \r\npublic static const F" +
            "13:uint = 124\r\n\r\nConstant associated with the key code value for the F13 key (12" +
            "4).\r\nF14\tConstant\t \r\npublic static const F14:uint = 125\r\n\r\nConstant associated w" +
            "ith the key code value for the F14 key (125).\r\nF15\tConstant\t \r\npublic static con" +
            "st F15:uint = 126\r\n\r\nConstant associated with the key code value for the F15 key" +
            " (126).\r\nF2\tConstant\t \r\npublic static const F2:uint = 113\r\n\r\nConstant associated" +
            " with the key code value for the F2 key (113).\r\nF3\tConstant\t \r\npublic static con" +
            "st F3:uint = 114\r\n\r\nConstant associated with the key code value for the F3 key (" +
            "114).\r\nF4\tConstant\t \r\npublic static const F4:uint = 115\r\n\r\nConstant associated w" +
            "ith the key code value for the F4 key (115).\r\nF5\tConstant\t \r\npublic static const" +
            " F5:uint = 116\r\n\r\nConstant associated with the key code value for the F5 key (11" +
            "6).\r\nF6\tConstant\t \r\npublic static const F6:uint = 117\r\n\r\nConstant associated wit" +
            "h the key code value for the F6 key (117).\r\nF7\tConstant\t \r\npublic static const F" +
            "7:uint = 118\r\n\r\nConstant associated with the key code value for the F7 key (118)" +
            ".\r\nF8\tConstant\t \r\npublic static const F8:uint = 119\r\n\r\nConstant associated with " +
            "the key code value for the F8 key (119).\r\nF9\tConstant\t \r\npublic static const F9:" +
            "uint = 120\r\n\r\nConstant associated with the key code value for the F9 key (120).\r" +
            "\nAIR-only G\tConstant\t \r\npublic static const G:uint = 71\r\n\r\nConstant associated w" +
            "ith the key code value for the G key (71).\r\nAIR-only H\tConstant\t \r\npublic static" +
            " const H:uint = 72\r\n\r\nConstant associated with the key code value for the H key " +
            "(72).\r\nHOME\tConstant\t \r\npublic static const HOME:uint = 36\r\n\r\nConstant associate" +
            "d with the key code value for the Home key (36).\r\nAIR-only I\tConstant\t \r\npublic " +
            "static const I:uint = 73\r\n\r\nConstant associated with the key code value for the " +
            "I key (73).\r\nINSERT\tConstant\t \r\npublic static const INSERT:uint = 45\r\n\r\nConstant" +
            " associated with the key code value for the Insert key (45).\r\nAIR-only J\tConstan" +
            "t\t \r\npublic static const J:uint = 74\r\n\r\nConstant associated with the key code va" +
            "lue for the J key (74).\r\nAIR-only K\tConstant\t \r\npublic static const K:uint = 75\r" +
            "\n\r\nConstant associated with the key code value for the K key (75).\r\nAIR-only KEY" +
            "NAME_BEGIN\tConstant\t \r\npublic static const KEYNAME_BEGIN:String = \"Begin\"\r\nAIR-o" +
            "nly KEYNAME_BREAK\tConstant\t \r\npublic static const KEYNAME_BREAK:String = \"Break\"" +
            "\r\nAIR-only KEYNAME_CLEARDISPLAY\tConstant\t \r\npublic static const KEYNAME_CLEARDIS" +
            "PLAY:String = \"ClrDsp\"\r\nAIR-only KEYNAME_CLEARLINE\tConstant\t \r\npublic static con" +
            "st KEYNAME_CLEARLINE:String = \"ClrLn\"\r\nAIR-only KEYNAME_DELETE\tConstant\t \r\npubli" +
            "c static const KEYNAME_DELETE:String = \"Delete\"\r\nAIR-only KEYNAME_DELETECHAR\tCon" +
            "stant\t \r\npublic static const KEYNAME_DELETECHAR:String = \"DelChr\"\r\nAIR-only KEYN" +
            "AME_DELETELINE\tConstant\t \r\npublic static const KEYNAME_DELETELINE:String = \"DelL" +
            "n\"\r\nAIR-only KEYNAME_DOWNARROW\tConstant\t \r\npublic static const KEYNAME_DOWNARROW" +
            ":String = \"Down\"\r\nAIR-only KEYNAME_END\tConstant\t \r\npublic static const KEYNAME_E" +
            "ND:String = \"End\"\r\nAIR-only KEYNAME_EXECUTE\tConstant\t \r\npublic static const KEYN" +
            "AME_EXECUTE:String = \"Exec\"\r\nAIR-only KEYNAME_F1\tConstant\t \r\npublic static const" +
            " KEYNAME_F1:String = \"F1\"\r\nAIR-only KEYNAME_F10\tConstant\t \r\npublic static const " +
            "KEYNAME_F10:String = \"F10\"\r\nAIR-only KEYNAME_F11\tConstant\t \r\npublic static const" +
            " KEYNAME_F11:String = \"F11\"\r\nAIR-only KEYNAME_F12\tConstant\t \r\npublic static cons" +
            "t KEYNAME_F12:String = \"F12\"\r\nAIR-only KEYNAME_F13\tConstant\t \r\npublic static con" +
            "st KEYNAME_F13:String = \"F13\"\r\nAIR-only KEYNAME_F14\tConstant\t \r\npublic static co" +
            "nst KEYNAME_F14:String = \"F14\"\r\nAIR-only KEYNAME_F15\tConstant\t \r\npublic static c" +
            "onst KEYNAME_F15:String = \"F15\"\r\nAIR-only KEYNAME_F16\tConstant\t \r\npublic static " +
            "const KEYNAME_F16:String = \"F16\"\r\nAIR-only KEYNAME_F17\tConstant\t \r\npublic static" +
            " const KEYNAME_F17:String = \"F17\"\r\nAIR-only KEYNAME_F18\tConstant\t \r\npublic stati" +
            "c const KEYNAME_F18:String = \"F18\"\r\nAIR-only KEYNAME_F19\tConstant\t \r\npublic stat" +
            "ic const KEYNAME_F19:String = \"F19\"\r\nAIR-only KEYNAME_F2\tConstant\t \r\npublic stat" +
            "ic const KEYNAME_F2:String = \"F2\"\r\nAIR-only KEYNAME_F20\tConstant\t \r\npublic stati" +
            "c const KEYNAME_F20:String = \"F20\"\r\nAIR-only KEYNAME_F21\tConstant\t \r\npublic stat" +
            "ic const KEYNAME_F21:String = \"F21\"\r\nAIR-only KEYNAME_F22\tConstant\t \r\npublic sta" +
            "tic const KEYNAME_F22:String = \"F22\"\r\nAIR-only KEYNAME_F23\tConstant\t \r\npublic st" +
            "atic const KEYNAME_F23:String = \"F23\"\r\nAIR-only KEYNAME_F24\tConstant\t \r\npublic s" +
            "tatic const KEYNAME_F24:String = \"F24\"\r\nAIR-only KEYNAME_F25\tConstant\t \r\npublic " +
            "static const KEYNAME_F25:String = \"F25\"\r\nAIR-only KEYNAME_F26\tConstant\t \r\npublic" +
            " static const KEYNAME_F26:String = \"F26\"\r\nAIR-only KEYNAME_F27\tConstant\t \r\npubli" +
            "c static const KEYNAME_F27:String = \"F27\"\r\nAIR-only KEYNAME_F28\tConstant\t \r\npubl" +
            "ic static const KEYNAME_F28:String = \"F28\"\r\nAIR-only KEYNAME_F29\tConstant\t \r\npub" +
            "lic static const KEYNAME_F29:String = \"F29\"\r\nAIR-only KEYNAME_F3\tConstant\t \r\npub" +
            "lic static const KEYNAME_F3:String = \"F3\"\r\nAIR-only KEYNAME_F30\tConstant\t \r\npubl" +
            "ic static const KEYNAME_F30:String = \"F30\"\r\nAIR-only KEYNAME_F31\tConstant\t \r\npub" +
            "lic static const KEYNAME_F31:String = \"F31\"\r\nAIR-only KEYNAME_F32\tConstant\t \r\npu" +
            "blic static const KEYNAME_F32:String = \"F32\"\r\nAIR-only KEYNAME_F33\tConstant\t \r\np" +
            "ublic static const KEYNAME_F33:String = \"F33\"\r\nAIR-only KEYNAME_F34\tConstant\t \r\n" +
            "public static const KEYNAME_F34:String = \"F34\"\r\nAIR-only KEYNAME_F35\tConstant\t \r" +
            "\npublic static const KEYNAME_F35:String = \"F35\"\r\nAIR-only KEYNAME_F4\tConstant\t \r" +
            "\npublic static const KEYNAME_F4:String = \"F4\"\r\nAIR-only KEYNAME_F5\tConstant\t \r\np" +
            "ublic static const KEYNAME_F5:String = \"F5\"\r\nAIR-only KEYNAME_F6\tConstant\t \r\npub" +
            "lic static const KEYNAME_F6:String = \"F6\"\r\nAIR-only KEYNAME_F7\tConstant\t \r\npubli" +
            "c static const KEYNAME_F7:String = \"F7\"\r\nAIR-only KEYNAME_F8\tConstant\t \r\npublic " +
            "static const KEYNAME_F8:String = \"F8\"\r\nAIR-only KEYNAME_F9\tConstant\t \r\npublic st" +
            "atic const KEYNAME_F9:String = \"F9\"\r\nAIR-only KEYNAME_FIND\tConstant\t \r\npublic st" +
            "atic const KEYNAME_FIND:String = \"Find\"\r\nAIR-only KEYNAME_HELP\tConstant\t \r\npubli" +
            "c static const KEYNAME_HELP:String = \"Help\"\r\nAIR-only KEYNAME_HOME\tConstant\t \r\np" +
            "ublic static const KEYNAME_HOME:String = \"Home\"\r\nAIR-only KEYNAME_INSERT\tConstan" +
            "t\t \r\npublic static const KEYNAME_INSERT:String = \"Insert\"\r\nAIR-only KEYNAME_INSE" +
            "RTCHAR\tConstant\t \r\npublic static const KEYNAME_INSERTCHAR:String = \"InsChr\"\r\nAIR" +
            "-only KEYNAME_INSERTLINE\tConstant\t \r\npublic static const KEYNAME_INSERTLINE:Stri" +
            "ng = \"InsLn\"\r\nAIR-only KEYNAME_LEFTARROW\tConstant\t \r\npublic static const KEYNAME" +
            "_LEFTARROW:String = \"Left\"\r\nAIR-only KEYNAME_MENU\tConstant\t \r\npublic static cons" +
            "t KEYNAME_MENU:String = \"Menu\"\r\nAIR-only KEYNAME_MODESWITCH\tConstant\t \r\npublic s" +
            "tatic const KEYNAME_MODESWITCH:String = \"ModeSw\"\r\nAIR-only KEYNAME_NEXT\tConstant" +
            "\t \r\npublic static const KEYNAME_NEXT:String = \"Next\"\r\nAIR-only KEYNAME_PAGEDOWN\t" +
            "Constant\t \r\npublic static const KEYNAME_PAGEDOWN:String = \"PgDn\"\r\nAIR-only KEYNA" +
            "ME_PAGEUP\tConstant\t \r\npublic static const KEYNAME_PAGEUP:String = \"PgUp\"\r\nAIR-on" +
            "ly KEYNAME_PAUSE\tConstant\t \r\npublic static const KEYNAME_PAUSE:String = \"Pause\"\r" +
            "\nAIR-only KEYNAME_PREV\tConstant\t \r\npublic static const KEYNAME_PREV:String = \"Pr" +
            "ev\"\r\nAIR-only KEYNAME_PRINT\tConstant\t \r\npublic static const KEYNAME_PRINT:String" +
            " = \"Print\"\r\nAIR-only KEYNAME_PRINTSCREEN\tConstant\t \r\npublic static const KEYNAME" +
            "_PRINTSCREEN:String = \"PrntScrn\"\r\nAIR-only KEYNAME_REDO\tConstant\t \r\npublic stati" +
            "c const KEYNAME_REDO:String = \"Redo\"\r\nAIR-only KEYNAME_RESET\tConstant\t \r\npublic " +
            "static const KEYNAME_RESET:String = \"Reset\"\r\nAIR-only KEYNAME_RIGHTARROW\tConstan" +
            "t\t \r\npublic static const KEYNAME_RIGHTARROW:String = \"Right\"\r\nAIR-only KEYNAME_S" +
            "CROLLLOCK\tConstant\t \r\npublic static const KEYNAME_SCROLLLOCK:String = \"ScrlLck\"\r" +
            "\nAIR-only KEYNAME_SELECT\tConstant\t \r\npublic static const KEYNAME_SELECT:String =" +
            " \"Select\"\r\nAIR-only KEYNAME_STOP\tConstant\t \r\npublic static const KEYNAME_STOP:St" +
            "ring = \"Stop\"\r\nAIR-only KEYNAME_SYSREQ\tConstant\t \r\npublic static const KEYNAME_S" +
            "YSREQ:String = \"SysReq\"\r\nAIR-only KEYNAME_SYSTEM\tConstant\t \r\npublic static const" +
            " KEYNAME_SYSTEM:String = \"Sys\"\r\nAIR-only KEYNAME_UNDO\tConstant\t \r\npublic static " +
            "const KEYNAME_UNDO:String = \"Undo\"\r\nAIR-only KEYNAME_UPARROW\tConstant\t \r\npublic " +
            "static const KEYNAME_UPARROW:String = \"Up\"\r\nAIR-only KEYNAME_USER\tConstant\t \r\npu" +
            "blic static const KEYNAME_USER:String = \"User\"\r\nAIR-only L\tConstant\t \r\npublic st" +
            "atic const L:uint = 76\r\n\r\nConstant associated with the key code value for the L " +
            "key (76).\r\nLEFT\tConstant\t \r\npublic static const LEFT:uint = 37\r\n\r\nConstant assoc" +
            "iated with the key code value for the Left Arrow key (37).\r\nAIR-only LEFTBRACKET" +
            "\tConstant\t \r\npublic static const LEFTBRACKET:uint = 219\r\n\r\nConstant associated w" +
            "ith the key code value for the [ key (219).\r\nAIR-only M\tConstant\t \r\npublic stati" +
            "c const M:uint = 77\r\n\r\nConstant associated with the key code value for the M key" +
            " (77).\r\nAIR-only MINUS\tConstant\t \r\npublic static const MINUS:uint = 189\r\n\r\nConst" +
            "ant associated with the key code value for the - key (189).\r\nAIR-only N\tConstant" +
            "\t \r\npublic static const N:uint = 78\r\n\r\nConstant associated with the key code val" +
            "ue for the N key (78).\r\nAIR-only NUMBER_0\tConstant\t \r\npublic static const NUMBER" +
            "_0:uint = 48\r\n\r\nConstant associated with the key code value for the 0 key (48).\r" +
            "\nAIR-only NUMBER_1\tConstant\t \r\npublic static const NUMBER_1:uint = 49\r\n\r\nConstan" +
            "t associated with the key code value for the 1 key (49).\r\nAIR-only NUMBER_2\tCons" +
            "tant\t \r\npublic static const NUMBER_2:uint = 50\r\n\r\nConstant associated with the k" +
            "ey code value for the 2 key (50).\r\nAIR-only NUMBER_3\tConstant\t \r\npublic static c" +
            "onst NUMBER_3:uint = 51\r\n\r\nConstant associated with the key code value for the 3" +
            " key (51).\r\nAIR-only NUMBER_4\tConstant\t \r\npublic static const NUMBER_4:uint = 52" +
            "\r\n\r\nConstant associated with the key code value for the 4 key (52).\r\nAIR-only NU" +
            "MBER_5\tConstant\t \r\npublic static const NUMBER_5:uint = 53\r\n\r\nConstant associated" +
            " with the key code value for the 5 key (53).\r\nAIR-only NUMBER_6\tConstant\t \r\npubl" +
            "ic static const NUMBER_6:uint = 54\r\n\r\nConstant associated with the key code valu" +
            "e for the 6 key (54).\r\nAIR-only NUMBER_7\tConstant\t \r\npublic static const NUMBER_" +
            "7:uint = 55\r\n\r\nConstant associated with the key code value for the 7 key (55).\r\n" +
            "AIR-only NUMBER_8\tConstant\t \r\npublic static const NUMBER_8:uint = 56\r\n\r\nConstant" +
            " associated with the key code value for the 8 key (56).\r\nAIR-only NUMBER_9\tConst" +
            "ant\t \r\npublic static const NUMBER_9:uint = 57\r\n\r\nConstant associated with the ke" +
            "y code value for the 9 key (57).\r\nAIR-only NUMPAD\tConstant\t \r\npublic static cons" +
            "t NUMPAD:uint = 21\r\n\r\nConstant associated with the pseudo-key code for the the n" +
            "umber pad (21). Use to set numpad modifier on key equivalents\r\nNUMPAD_0\tConstant" +
            "\t \r\npublic static const NUMPAD_0:uint = 96\r\n\r\nConstant associated with the key c" +
            "ode value for the number 0 key on the number pad (96).\r\nNUMPAD_1\tConstant\t \r\npub" +
            "lic static const NUMPAD_1:uint = 97\r\n\r\nConstant associated with the key code val" +
            "ue for the number 1 key on the number pad (97).\r\nNUMPAD_2\tConstant\t \r\npublic sta" +
            "tic const NUMPAD_2:uint = 98\r\n\r\nConstant associated with the key code value for " +
            "the number 2 key on the number pad (98).\r\nNUMPAD_3\tConstant\t \r\npublic static con" +
            "st NUMPAD_3:uint = 99\r\n\r\nConstant associated with the key code value for the num" +
            "ber 3 key on the number pad (99).\r\nNUMPAD_4\tConstant\t \r\npublic static const NUMP" +
            "AD_4:uint = 100\r\n\r\nConstant associated with the key code value for the number 4 " +
            "key on the number pad (100).\r\nNUMPAD_5\tConstant\t \r\npublic static const NUMPAD_5:" +
            "uint = 101\r\n\r\nConstant associated with the key code value for the number 5 key o" +
            "n the number pad (101).\r\nNUMPAD_6\tConstant\t \r\npublic static const NUMPAD_6:uint " +
            "= 102\r\n\r\nConstant associated with the key code value for the number 6 key on the" +
            " number pad (102).\r\nNUMPAD_7\tConstant\t \r\npublic static const NUMPAD_7:uint = 103" +
            "\r\n\r\nConstant associated with the key code value for the number 7 key on the numb" +
            "er pad (103).\r\nNUMPAD_8\tConstant\t \r\npublic static const NUMPAD_8:uint = 104\r\n\r\nC" +
            "onstant associated with the key code value for the number 8 key on the number pa" +
            "d (104).\r\nNUMPAD_9\tConstant\t \r\npublic static const NUMPAD_9:uint = 105\r\n\r\nConsta" +
            "nt associated with the key code value for the number 9 key on the number pad (10" +
            "5).\r\nNUMPAD_ADD\tConstant\t \r\npublic static const NUMPAD_ADD:uint = 107\r\n\r\nConstan" +
            "t associated with the key code value for the addition key on the number pad (107" +
            ").\r\nNUMPAD_DECIMAL\tConstant\t \r\npublic static const NUMPAD_DECIMAL:uint = 110\r\n\r\n" +
            "Constant associated with the key code value for the decimal key on the number pa" +
            "d (110).\r\nNUMPAD_DIVIDE\tConstant\t \r\npublic static const NUMPAD_DIVIDE:uint = 111" +
            "\r\n\r\nConstant associated with the key code value for the division key on the numb" +
            "er pad (111).\r\nNUMPAD_ENTER\tConstant\t \r\npublic static const NUMPAD_ENTER:uint = " +
            "108\r\n\r\nConstant associated with the key code value for the Enter key on the numb" +
            "er pad (108).\r\nNUMPAD_MULTIPLY\tConstant\t \r\npublic static const NUMPAD_MULTIPLY:u" +
            "int = 106\r\n\r\nConstant associated with the key code value for the multiplication " +
            "key on the number pad (106).\r\nNUMPAD_SUBTRACT\tConstant\t \r\npublic static const NU" +
            "MPAD_SUBTRACT:uint = 109\r\n\r\nConstant associated with the key code value for the " +
            "subtraction key on the number pad (109).\r\nAIR-only O\tConstant\t \r\npublic static c" +
            "onst O:uint = 79\r\n\r\nConstant associated with the key code value for the O key (7" +
            "9).\r\nAIR-only P\tConstant\t \r\npublic static const P:uint = 80\r\n\r\nConstant associat" +
            "ed with the key code value for the P key (80).\r\nPAGE_DOWN\tConstant\t \r\npublic sta" +
            "tic const PAGE_DOWN:uint = 34\r\n\r\nConstant associated with the key code value for" +
            " the Page Down key (34).\r\nPAGE_UP\tConstant\t \r\npublic static const PAGE_UP:uint =" +
            " 33\r\n\r\nConstant associated with the key code value for the Page Up key (33).\r\nAI" +
            "R-only PERIOD\tConstant\t \r\npublic static const PERIOD:uint = 190\r\n\r\nConstant asso" +
            "ciated with the key code value for the . key (190).\r\nAIR-only Q\tConstant\t \r\npubl" +
            "ic static const Q:uint = 81\r\n\r\nConstant associated with the key code value for t" +
            "he Q key (81).\r\nAIR-only QUOTE\tConstant\t \r\npublic static const QUOTE:uint = 222\r" +
            "\n\r\nConstant associated with the key code value for the \' key (222).\r\nAIR-only R\t" +
            "Constant\t \r\npublic static const R:uint = 82\r\n\r\nConstant associated with the key " +
            "code value for the R key (82).\r\nRIGHT\tConstant\t \r\npublic static const RIGHT:uint" +
            " = 39\r\n\r\nConstant associated with the key code value for the Right Arrow key (39" +
            ").\r\nAIR-only RIGHTBRACKET\tConstant\t \r\npublic static const RIGHTBRACKET:uint = 22" +
            "1\r\n\r\nConstant associated with the key code value for the ] key (221).\r\nAIR-only " +
            "S\tConstant\t \r\npublic static const S:uint = 83\r\n\r\nConstant associated with the ke" +
            "y code value for the S key (83).\r\nAIR-only SEMICOLON\tConstant\t \r\npublic static c" +
            "onst SEMICOLON:uint = 186\r\n\r\nConstant associated with the key code value for the" +
            " ; key (186).\r\nSHIFT\tConstant\t \r\npublic static const SHIFT:uint = 16\r\n\r\nConstant" +
            " associated with the key code value for the Shift key (16).\r\nAIR-only SLASH\tCons" +
            "tant\t \r\npublic static const SLASH:uint = 191\r\n\r\nConstant associated with the key" +
            " code value for the / key (191).\r\nSPACE\tConstant\t \r\npublic static const SPACE:ui" +
            "nt = 32\r\n\r\nConstant associated with the key code value for the Spacebar (32).\r\nA" +
            "IR-only STRING_BEGIN\tConstant\t \r\npublic static const STRING_BEGIN:String = \"?\"\r\n" +
            "AIR-only STRING_BREAK\tConstant\t \r\npublic static const STRING_BREAK:String = \"?\"\r" +
            "\nAIR-only STRING_CLEARDISPLAY\tConstant\t \r\npublic static const STRING_CLEARDISPLA" +
            "Y:String = \"?\"\r\nAIR-only STRING_CLEARLINE\tConstant\t \r\npublic static const STRING" +
            "_CLEARLINE:String = \"?\"\r\nAIR-only STRING_DELETE\tConstant\t \r\npublic static const " +
            "STRING_DELETE:String = \"?\"\r\nAIR-only STRING_DELETECHAR\tConstant\t \r\npublic static" +
            " const STRING_DELETECHAR:String = \"?\"\r\nAIR-only STRING_DELETELINE\tConstant\t \r\npu" +
            "blic static const STRING_DELETELINE:String = \"?\"\r\nAIR-only STRING_DOWNARROW\tCons" +
            "tant\t \r\npublic static const STRING_DOWNARROW:String = \"?\"\r\nAIR-only STRING_END\tC" +
            "onstant\t \r\npublic static const STRING_END:String = \"?\"\r\nAIR-only STRING_EXECUTE\t" +
            "Constant\t \r\npublic static const STRING_EXECUTE:String = \"?\"\r\nAIR-only STRING_F1\t" +
            "Constant\t \r\npublic static const STRING_F1:String = \"?\"\r\nAIR-only STRING_F10\tCons" +
            "tant\t \r\npublic static const STRING_F10:String = \"?\"\r\nAIR-only STRING_F11\tConstan" +
            "t\t \r\npublic static const STRING_F11:String = \"?\"\r\nAIR-only STRING_F12\tConstant\t " +
            "\r\npublic static const STRING_F12:String = \"?\"\r\nAIR-only STRING_F13\tConstant\t \r\np" +
            "ublic static const STRING_F13:String = \"?\"\r\nAIR-only STRING_F14\tConstant\t \r\npubl" +
            "ic static const STRING_F14:String = \"?\"\r\nAIR-only STRING_F15\tConstant\t \r\npublic " +
            "static const STRING_F15:String = \"?\"\r\nAIR-only STRING_F16\tConstant\t \r\npublic sta" +
            "tic const STRING_F16:String = \"?\"\r\nAIR-only STRING_F17\tConstant\t \r\npublic static" +
            " const STRING_F17:String = \"?\"\r\nAIR-only STRING_F18\tConstant\t \r\npublic static co" +
            "nst STRING_F18:String = \"?\"\r\nAIR-only STRING_F19\tConstant\t \r\npublic static const" +
            " STRING_F19:String = \"?\"\r\nAIR-only STRING_F2\tConstant\t \r\npublic static const STR" +
            "ING_F2:String = \"?\"\r\nAIR-only STRING_F20\tConstant\t \r\npublic static const STRING_" +
            "F20:String = \"?\"\r\nAIR-only STRING_F21\tConstant\t \r\npublic static const STRING_F21" +
            ":String = \"?\"\r\nAIR-only STRING_F22\tConstant\t \r\npublic static const STRING_F22:St" +
            "ring = \"?\"\r\nAIR-only STRING_F23\tConstant\t \r\npublic static const STRING_F23:Strin" +
            "g = \"?\"\r\nAIR-only STRING_F24\tConstant\t \r\npublic static const STRING_F24:String =" +
            " \"?\"\r\nAIR-only STRING_F25\tConstant\t \r\npublic static const STRING_F25:String = \"?" +
            "\"\r\nAIR-only STRING_F26\tConstant\t \r\npublic static const STRING_F26:String = \"?\"\r\n" +
            "AIR-only STRING_F27\tConstant\t \r\npublic static const STRING_F27:String = \"?\"\r\nAIR" +
            "-only STRING_F28\tConstant\t \r\npublic static const STRING_F28:String = \"?\"\r\nAIR-on" +
            "ly STRING_F29\tConstant\t \r\npublic static const STRING_F29:String = \"?\"\r\nAIR-only " +
            "STRING_F3\tConstant\t \r\npublic static const STRING_F3:String = \"?\"\r\nAIR-only STRIN" +
            "G_F30\tConstant\t \r\npublic static const STRING_F30:String = \"?\"\r\nAIR-only STRING_F" +
            "31\tConstant\t \r\npublic static const STRING_F31:String = \"?\"\r\nAIR-only STRING_F32\t" +
            "Constant\t \r\npublic static const STRING_F32:String = \"?\"\r\nAIR-only STRING_F33\tCon" +
            "stant\t \r\npublic static const STRING_F33:String = \"?\"\r\nAIR-only STRING_F34\tConsta" +
            "nt\t \r\npublic static const STRING_F34:String = \"?\"\r\nAIR-only STRING_F35\tConstant\t" +
            " \r\npublic static const STRING_F35:String = \"?\"\r\nAIR-only STRING_F4\tConstant\t \r\np" +
            "ublic static const STRING_F4:String = \"?\"\r\nAIR-only STRING_F5\tConstant\t \r\npublic" +
            " static const STRING_F5:String = \"?\"\r\nAIR-only STRING_F6\tConstant\t \r\npublic stat" +
            "ic const STRING_F6:String = \"?\"\r\nAIR-only STRING_F7\tConstant\t \r\npublic static co" +
            "nst STRING_F7:String = \"?\"\r\nAIR-only STRING_F8\tConstant\t \r\npublic static const S" +
            "TRING_F8:String = \"?\"\r\nAIR-only STRING_F9\tConstant\t \r\npublic static const STRING" +
            "_F9:String = \"?\"\r\nAIR-only STRING_FIND\tConstant\t \r\npublic static const STRING_FI" +
            "ND:String = \"?\"\r\nAIR-only STRING_HELP\tConstant\t \r\npublic static const STRING_HEL" +
            "P:String = \"?\"\r\nAIR-only STRING_HOME\tConstant\t \r\npublic static const STRING_HOME" +
            ":String = \"?\"\r\nAIR-only STRING_INSERT\tConstant\t \r\npublic static const STRING_INS" +
            "ERT:String = \"?\"\r\nAIR-only STRING_INSERTCHAR\tConstant\t \r\npublic static const STR" +
            "ING_INSERTCHAR:String = \"?\"\r\nAIR-only STRING_INSERTLINE\tConstant\t \r\npublic stati" +
            "c const STRING_INSERTLINE:String = \"?\"\r\nAIR-only STRING_LEFTARROW\tConstant\t \r\npu" +
            "blic static const STRING_LEFTARROW:String = \"?\"\r\nAIR-only STRING_MENU\tConstant\t " +
            "\r\npublic static const STRING_MENU:String = \"?\"\r\nAIR-only STRING_MODESWITCH\tConst" +
            "ant\t \r\npublic static const STRING_MODESWITCH:String = \"?\"\r\nAIR-only STRING_NEXT\t" +
            "Constant\t \r\npublic static const STRING_NEXT:String = \"?\"\r\nAIR-only STRING_PAGEDO" +
            "WN\tConstant\t \r\npublic static const STRING_PAGEDOWN:String = \"?\"\r\nAIR-only STRING" +
            "_PAGEUP\tConstant\t \r\npublic static const STRING_PAGEUP:String = \"?\"\r\nAIR-only STR" +
            "ING_PAUSE\tConstant\t \r\npublic static const STRING_PAUSE:String = \"?\"\r\nAIR-only ST" +
            "RING_PREV\tConstant\t \r\npublic static const STRING_PREV:String = \"?\"\r\nAIR-only STR" +
            "ING_PRINT\tConstant\t \r\npublic static const STRING_PRINT:String = \"?\"\r\nAIR-only ST" +
            "RING_PRINTSCREEN\tConstant\t \r\npublic static const STRING_PRINTSCREEN:String = \"?\"" +
            "\r\nAIR-only STRING_REDO\tConstant\t \r\npublic static const STRING_REDO:String = \"?\"\r" +
            "\nAIR-only STRING_RESET\tConstant\t \r\npublic static const STRING_RESET:String = \"?\"" +
            "\r\nAIR-only STRING_RIGHTARROW\tConstant\t \r\npublic static const STRING_RIGHTARROW:S" +
            "tring = \"?\"\r\nAIR-only STRING_SCROLLLOCK\tConstant\t \r\npublic static const STRING_S" +
            "CROLLLOCK:String = \"?\"\r\nAIR-only STRING_SELECT\tConstant\t \r\npublic static const S" +
            "TRING_SELECT:String = \"?\"\r\nAIR-only STRING_STOP\tConstant\t \r\npublic static const " +
            "STRING_STOP:String = \"?\"\r\nAIR-only STRING_SYSREQ\tConstant\t \r\npublic static const" +
            " STRING_SYSREQ:String = \"?\"\r\nAIR-only STRING_SYSTEM\tConstant\t \r\npublic static co" +
            "nst STRING_SYSTEM:String = \"?\"\r\nAIR-only STRING_UNDO\tConstant\t \r\npublic static c" +
            "onst STRING_UNDO:String = \"?\"\r\nAIR-only STRING_UPARROW\tConstant\t \r\npublic static" +
            " const STRING_UPARROW:String = \"?\"\r\nAIR-only STRING_USER\tConstant\t \r\npublic stat" +
            "ic const STRING_USER:String = \"?\"\r\nAIR-only T\tConstant\t \r\npublic static const T:" +
            "uint = 84\r\n\r\nConstant associated with the key code value for the T key (84).\r\nTA" +
            "B\tConstant\t \r\npublic static const TAB:uint = 9\r\n\r\nConstant associated with the k" +
            "ey code value for the Tab key (9).\r\nAIR-only U\tConstant\t \r\npublic static const U" +
            ":uint = 85\r\n\r\nConstant associated with the key code value for the U key (85).\r\nU" +
            "P\tConstant\t \r\npublic static const UP:uint = 38\r\n\r\nConstant associated with the k" +
            "ey code value for the Up Arrow key (38).\r\nAIR-only V\tConstant\t \r\npublic static c" +
            "onst V:uint = 86\r\n\r\nConstant associated with the key code value for the V key (8" +
            "6).\r\nAIR-only W\tConstant\t \r\npublic static const W:uint = 87\r\n\r\nConstant associat" +
            "ed with the key code value for the W key (87).\r\nAIR-only X\tConstant\t \r\npublic st" +
            "atic const X:uint = 88\r\n\r\nConstant associated with the key code value for the X " +
            "key (88).\r\nAIR-only Y\tConstant\t \r\npublic static const Y:uint = 89\r\n\r\nConstant as" +
            "sociated with the key code value for the Y key (89).\r\nAIR-only Z\tConstant\t \r\npub" +
            "lic static const Z:uint = 90\r\n\r\nConstant associated with the key code value for " +
            "the Z key (90).\r\n\r\n\r\n\r\nCurrent Page: http://livedocs.adobe.com/flex/3/langref/fl" +
            "ash/ui/Keyboard.html\r\n© 2004-2008 Adobe Systems Incorporated. All rights reserve" +
            "d.\r\nFri Jan 25 2008, 2:58 PM GMT-05:00\r\nKeyboard Keyboard Keyboard Keyboard Keyb" +
            "oard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Key" +
            "board Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Ke" +
            "yboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard K" +
            "eyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard " +
            "Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard" +
            " Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboar" +
            "d Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboa" +
            "rd Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keybo" +
            "ard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyb" +
            "oard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Key" +
            "board Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Ke" +
            "yboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard K" +
            "eyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard " +
            "Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard" +
            " Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboar" +
            "d Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboa" +
            "rd Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keybo" +
            "ard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyb" +
            "oard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Key" +
            "board Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Ke" +
            "yboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard K" +
            "eyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard " +
            "Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard" +
            " Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboar" +
            "d Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboa" +
            "rd Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keybo" +
            "ard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyb" +
            "oard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Key" +
            "board Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Ke" +
            "yboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard K" +
            "eyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard " +
            "Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard" +
            " Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboar" +
            "d Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboa" +
            "rd Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keybo" +
            "ard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyb" +
            "oard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Key" +
            "board Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Ke" +
            "yboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard K" +
            "eyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard " +
            "Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard" +
            " Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboar" +
            "d Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboa" +
            "rd Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keybo" +
            "ard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyb" +
            "oard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Key" +
            "board Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Ke" +
            "yboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard K" +
            "eyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard " +
            "Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard" +
            " Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboar" +
            "d Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboa" +
            "rd Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keybo" +
            "ard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyb" +
            "oard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard Key" +
            "board Keyboard Keyboard Keyboard Keyboard Keyboard Keyboard\r\nflash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash" +
            ".ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyb" +
            "oard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard fla" +
            "sh.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Ke" +
            "yboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard f" +
            "lash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui." +
            "Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard" +
            " flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.u" +
            "i.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboard flash.ui.Keyboa" +
            "rd flash.ui.Keyboard\r\nComments\r\n\r\n    * There are no comments yet. Be the first " +
            "to add a comment on this article.\r\n    * You need to sign in in order to post a " +
            "comment.\r\n\r\nAdd Comment\r\n﻿")]
        public string TestInput {
            get {
                return ((string)(this["TestInput"]));
            }
            set {
                this["TestInput"] = value;
            }
        }
    }
}
