// http://developer.chrome.com/trunk/apps/api_index.html


// http://developer.chrome.com/trunk/apps/app.window.html#type-AppWindow
[Constructor]
interface AppWindow 
{

		void restore();
		void moveTo();
		void clearAttention();
		void minimize();
		void drawAttention();
		void focus();
		void resizeTo();
		void maximize();

		readonly attribute WindowProxy? contentWindow;
};
