// Generated by ScriptCoreLib.Alchemy.ExportGenerator
// Clear this file to force code generation.
namespace cmodule.FlashPlasma
{
	using ScriptCoreLib;
	using ScriptCoreLib.ActionScript.flash.utils;
	using ScriptCoreLib.ActionScript.flash.display;
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[Script(IsNative = true)]
	public class CLibInit
	{
		public void supplyFile(string path, ByteArray data)
		{
		}
		public void putEnv(string key, string value)
		{
		}
		public void setSprite(Sprite sprite)
		{
		}
		public object init()
		{
			return default(object);
		}
	}
}
namespace FlashPlasma.Alchemy
{
	using ScriptCoreLib;
	using ScriptCoreLib.Alchemy.Headers;
	partial class AlchemyProgram
	{
		[global::System.Runtime.CompilerServices.CompilerGenerated]
		static AS3_h._AS3_Val generatePlasma(object self, AS3_h._AS3_Val args)
		{
			int width;
			int height;
			AS3_h.AS3_ArrayValue(args, "IntType, IntType", __arglist(out width, out height));
			var __value = FlashPlasmaEngine.Plasma.generatePlasma(width, height);
			width = default(int);
			height = default(int);
			return AS3_h.AS3_Ptr(__value);
		}
		[global::System.Runtime.CompilerServices.CompilerGenerated]
		static AS3_h._AS3_Val shiftPlasma(object self, AS3_h._AS3_Val args)
		{
			int shift;
			AS3_h.AS3_ArrayValue(args, "IntType", __arglist(out shift));
			var __value = FlashPlasmaEngine.Plasma.shiftPlasma(shift);
			shift = default(int);
			return AS3_h.AS3_Ptr(__value);
		}
		[global::System.Runtime.CompilerServices.CompilerGenerated]
		[Script(NoDecoration = true)]
		static int main()
		{
			var __generatePlasma = AS3_h.AS3_Function(null, generatePlasma);
			var __shiftPlasma = AS3_h.AS3_Function(null, shiftPlasma);
			var __result = AS3_h.AS3_Object("generatePlasma: AS3ValType,shiftPlasma: AS3ValType", __arglist(__generatePlasma,__shiftPlasma));
			AS3_h.AS3_Release(__generatePlasma);
			AS3_h.AS3_Release(__shiftPlasma);
			AS3_h.AS3_LibInit(__result);
			return 0;
		}
	}
}
namespace FlashPlasma.ActionScript
{
	using System;
	using ScriptCoreLib;
	using ScriptCoreLib.ActionScript;
	using ScriptCoreLib.ActionScript.Extensions;
	using ScriptCoreLib.ActionScript.flash.utils;
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[Script]
	public static class PlasmaProxy
	{
		public static ByteArray Memory;
		[Script(OptimizedCode = @"return (ns::gstate).ds")]
		public static ByteArray get_ds(Namespace ns)
		{
			return default(ByteArray);
		}
		public static readonly Func<int, int, uint> generatePlasma;
		public static readonly Func<int, uint> shiftPlasma;
		static PlasmaProxy()
		{
			var __loader = new cmodule.FlashPlasma.CLibInit();
			var __lib = new DynamicDelegatesContainer { Subject = __loader.init() };
			PlasmaProxy.Memory = get_ds(new Namespace("cmodule.FlashPlasma"));
			PlasmaProxy.generatePlasma = __lib.ToFunc<int, int, uint>("generatePlasma");
			PlasmaProxy.shiftPlasma = __lib.ToFunc<int, uint>("shiftPlasma");
		}
	}
}
