// http://developer.chrome.com/trunk/apps/api_index.html


// http://developer.chrome.com/trunk/apps/socket.html#type-SocketInfo
[Constructor]
interface SocketInfo 
{
	attribute DOMString peerAddress;
	attribute long peerPort;
		
	attribute DOMString localAddress;
	attribute long localPort;
		
	attribute boolean connected;
};

// http://developer.chrome.com/trunk/apps/socket.html#type-NetworkInterface
[Constructor]
interface NetworkInterface 
{
	attribute DOMString name ;
	attribute DOMString address ;
};

[Constructor]
interface ReadInfo 
{
	attribute long resultCode;
	attribute ArrayBufferView data;
};

[Constructor]
interface AcceptInfo 
{
	attribute long resultCode;
	attribute long socketId;
};

[Constructor]
interface WriteInfo 
{
	attribute long bytesWritten;
};


[Constructor]
interface RecvFromInfo 
{
	attribute long resultCode;
	attribute long port;
	attribute DOMString address;
	attribute ArrayBufferView data;
};

[Constructor]
interface CreateInfo 
{
	attribute long socketId;
};

[Constructor]
interface CreateOptions
{
};

