//$Id$

/**
 * Author : Moez Ben MBarka Moez
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/* Generated By:JavaCC: Do not edit this line. JGPShellConstants.java */
package com.jgpshell.shell;

public interface JGPShellConstants {

  int EOF = 0;
  int LS = 6;
  int CONNECT = 7;
  int SELECT = 8;
  int EXIT = 9;
  int SET = 10;
  int REINIT = 11;
  int ECHO = 12;
  int LIST_VARS = 13;
  int NEW_SESSION = 14;
  int THREADS = 15;
  int KILL = 16;
  int RUN = 17;
  int START = 18;
  int END = 19;
  int LS_C = 20;
  int CLOSE = 21;
  int INIT_UPDATE = 22;
  int EXT_AUTH = 23;
  int AUTHENTICATE = 24;
  int SEND = 25;
  int UPLOAD = 26;
  int INSTALL = 27;
  int DELETE = 28;
  int FORMAT = 29;
  int SELECT_C = 30;
  int FOR = 31;
  int READER = 32;
  int TO = 33;
  int BRACE_O = 34;
  int BRACE_C = 35;
  int PV = 36;
  int LOG = 37;
  int DOLLARD = 38;
  int H = 39;
  int HH = 40;
  int INT = 41;
  int HEXA = 42;
  int AID = 43;
  int TEXT = 44;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"/ls\"",
    "\"/connect\"",
    "\"/select\"",
    "\"/exit\"",
    "\"/set\"",
    "\"/reinit\"",
    "\"/echo\"",
    "\"/list-vars\"",
    "\"/new-session\"",
    "\"/threads\"",
    "\"/kill\"",
    "\"/run\"",
    "\"/start\"",
    "\"/end\"",
    "\"ls\"",
    "\"close\"",
    "\"init-update\"",
    "\"ext-auth\"",
    "\"authenticate\"",
    "\"send\"",
    "\"upload\"",
    "\"install\"",
    "\"delete\"",
    "\"format\"",
    "\"select\"",
    "\"for\"",
    "\"reader\"",
    "\"to\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"log\"",
    "\"$\"",
    "\"#\"",
    "\"##\"",
    "<INT>",
    "<HEXA>",
    "<AID>",
    "<TEXT>",
    "\"-p\"",
    "\"-h\"",
  };

}


