/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.majorkernelpanic.spydroid;

public final class R {
    public static final class array {
        public static final int audioEncoderArray=0x7f050002;
        public static final int audioEncoderValues=0x7f050003;
        /**  BITRATE 
         */
        public static final int videoBitrateArray=0x7f050007;
        public static final int videoBitrateValues=0x7f050008;
        public static final int videoEncoderArray=0x7f050000;
        public static final int videoEncoderValues=0x7f050001;
        /**  FRAMERATE 
         */
        public static final int videoFramerateArray=0x7f050005;
        public static final int videoFramerateValues=0x7f050006;
        /**  RESOLUTION 
         */
        public static final int videoResolutionArray=0x7f050004;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int ic_eye=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int options=0x7f020003;
    }
    public static final class id {
        public static final int console=0x7f080004;
        public static final int ip=0x7f080005;
        public static final int linearLayout=0x7f080002;
        public static final int logo=0x7f080003;
        public static final int mainlayout=0x7f080000;
        public static final int options=0x7f080006;
        public static final int smallcameraview=0x7f080001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class menu {
        public static final int menu=0x7f070000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
