using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using AutoGeneratedReferences.Library;
using System.Runtime.InteropServices;

namespace AutoGeneratedReferences
{
	public partial class Program
	{


		public static void Main(string[] args)
		{
			Console.WriteLine(
				new AutoGeneratedReferences.Components.Test3().Text
			);

			Console.WriteLine(
				new AutoGeneratedReferences.Components.Test2().Text
			);

			Console.WriteLine(
				new AutoGeneratedReferences.Components.Test1().Text
			);

			Console.WriteLine(
				new AutoGeneratedReferences.Components.JohDoe().Text
			);
		}


	}
}
