using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ScriptCoreLib;
using ScriptCoreLib.ActionScript.flash.utils;
using ScriptCoreLib.ActionScript.flash.display;

namespace cmodule.FlashAlchemyEcho
{
	[Script(IsNative = true)]
	public class CLibInit
	{
		// this class was generated by alchemy and
		// may be represented by 2664.achacks.as

		public void supplyFile(string path, ByteArray data)
		{
		}

		public void putEnv(string key, string value)
		{
		}

		public void setSprite(Sprite sprite)
		{
		}

		public object init()
		{
			return null;
		}
	}
}
