/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package wei.mark.standout;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int ics_blue=0x7f040000;
    }
    public static final class drawable {
        public static final int border=0x7f020000;
        public static final int border_focused=0x7f020001;
        public static final int close=0x7f020002;
        public static final int corner=0x7f020003;
        public static final int hide=0x7f020004;
        public static final int ic_launcher=0x7f020005;
    }
    public static final class id {
        public static final int View01=0x7f060002;
        public static final int View02=0x7f060001;
        public static final int background=0x7f060000;
        public static final int body=0x7f06000f;
        public static final int button=0x7f060014;
        public static final int close=0x7f06000e;
        public static final int content=0x7f060009;
        public static final int corner=0x7f060010;
        public static final int description=0x7f060006;
        public static final int edit=0x7f060012;
        public static final int edit2=0x7f060013;
        public static final int hide=0x7f06000d;
        public static final int icon=0x7f060005;
        public static final int id=0x7f060004;
        public static final int status=0x7f060011;
        public static final int textView1=0x7f060007;
        public static final int textView2=0x7f060008;
        public static final int title=0x7f06000c;
        public static final int titlebar=0x7f06000a;
        public static final int view1=0x7f060003;
        public static final int window_icon=0x7f06000b;
    }
    public static final class layout {
        public static final int body=0x7f030000;
        public static final int drop_down_list_item=0x7f030001;
        public static final int simple=0x7f030002;
        public static final int system_window_decorators=0x7f030003;
        public static final int widgets=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int close=0x7f050004;
        public static final int corner=0x7f050005;
        public static final int hello=0x7f050000;
        public static final int hide=0x7f050003;
        public static final int window_icon=0x7f050002;
    }
}
