/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package wei.mark.standout;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int border=0x7f020000;
        public static final int border_focused=0x7f020001;
        public static final int close=0x7f020002;
        public static final int corner=0x7f020003;
        public static final int hide=0x7f020004;
        public static final int ic_launcher=0x7f020005;
        public static final int maximize=0x7f020006;
    }
    public static final class id {
        public static final int View01=0x7f050002;
        public static final int View02=0x7f050001;
        public static final int background=0x7f050000;
        public static final int body=0x7f050010;
        public static final int button=0x7f050015;
        public static final int close=0x7f05000f;
        public static final int content=0x7f050009;
        public static final int corner=0x7f050011;
        public static final int description=0x7f050006;
        public static final int edit=0x7f050013;
        public static final int edit2=0x7f050014;
        public static final int hide=0x7f05000d;
        public static final int icon=0x7f050005;
        public static final int id=0x7f050004;
        public static final int maximize=0x7f05000e;
        public static final int status=0x7f050012;
        public static final int textView1=0x7f050007;
        public static final int textView2=0x7f050008;
        public static final int title=0x7f05000c;
        public static final int titlebar=0x7f05000a;
        public static final int view1=0x7f050003;
        public static final int window_icon=0x7f05000b;
    }
    public static final class layout {
        public static final int body=0x7f030000;
        public static final int drop_down_list_item=0x7f030001;
        public static final int simple=0x7f030002;
        public static final int system_window_decorators=0x7f030003;
        public static final int widgets=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int close=0x7f040003;
        public static final int corner=0x7f040004;
        public static final int hide=0x7f040002;
        public static final int maximize=0x7f040005;
        public static final int window_icon=0x7f040001;
    }
}
