using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using java.applet;
using ScriptCoreLib;
using ScriptCoreLib.ActionScript;
using ScriptCoreLib.ActionScript.flash.display;
using ScriptCoreLib.JavaScript.DOM.HTML;
using ScriptCoreLib.JavaScript.Extensions;
using ScriptCoreLib.JavaScript;
using ScriptCoreLib.ActionScript.Extensions;
using java.awt;
using ScriptCoreLib.JavaScript.DOM;
using System.ComponentModel;

namespace Ultra6
{

	//[Description("OrcasClientScriptApplication. Write javascript, flash and java applets within a C# project.")]



	public sealed class UltraApplication
	{
		public sealed class UltraApplet : Applet, IArgumentData1
		{
			public const int DefaultWidth = 500;
			public const int DefaultHeight = 400;


			public override void init()
			{
				base.resize(DefaultWidth, DefaultHeight);
				// creating the java applet

			}

			static Color GetBlue(double b)
			{
				int u = (int)(0xff * b);

				return new Color(u);
			}

			public override void paint(global::java.awt.Graphics g)
			{
				// old school gradient :)

				var h = this.getHeight();
				var w = this.getWidth();

				for (int i = 0; i < h; i++)
				{

					g.setColor(GetBlue(1 - (double)i / (double)h));
					g.drawLine(0, i, w, i);
				}
			}

			public Action1 AddSubject(IArgumentData1 e)
			{
				e.CalculateHere();

				return 
					x =>
					{
						x.CalculateHere();

						return "ok";
					};

			}

			public void AddSubjectTwice(IArgumentData1 e, Action1 f)
			{

			}

			public event Action1 AtEvent1;
			public string Status { get; set; }
		}



		public sealed class UltraSprite : Sprite, IArgumentData1
		{
			public const int DefaultWidth = 500;
			public const int DefaultHeight = 400;

			public UltraSprite()
			{
				// creating the flash object 
				// + stratus
				// + alchemy

				// funny :) i have forgotten how to write anything
				// on flash API ... too much WPF API?
				var r = new Sprite();

				r.graphics.beginFill(0x7070);
				r.graphics.drawRect(8, 8, 64, 64);


				r.AttachTo(this);
			}


			public Action1 AddSubject(IArgumentData1 e)
			{
				return null;
			}

			public void AddSubjectTwice(IArgumentData1 e, Action1 f)
			{

			}

			public event Action1 AtEvent1;

			public string Status { get; set; }
		}

		public UltraApplication(IHTMLElement e)
		{
			// we are attaching to the DOM now after onload event
			// bootstrap code was generated by jsc.meta and is using ScriptCoreLib

			{
				var x = new IHTMLButton("create UltraSprite proxied");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{
						var o = new UltraSprite();

						o.AttachSpriteToDocument();

						o.CalculateHere();
					};
			}

			{
				var x = new IHTMLButton("create UltraApplet proxied");

				x.AttachToDocument();

				x.onclick +=
					delegate
					{
						var o = new UltraApplet();

						o.AttachAppletToDocument();

						o.CalculateHere();
					};
			}

		}


	}

	public delegate string Action1(IArgumentData1 e);

	public interface IArgumentData1
	{
		string Status { get; set; }
	}

	public static class MyExtensions
	{
		public static void CalculateHere(this IArgumentData1 e)
		{
			// this method will appear in javascript, flash and java

			e.Status = "result";
		}
	}
}
